### ISSUE TITLE
Media playing position is not restored properly

### ISSUE THREAD

**Issue by jeremypw** [elementary/music#408] opened 2018-08-16 18:14 UTC
If the app is closed with a medium partly played (and continue playing turned off) then when reopened the medium position is returned to zero i.e. it starts playing from the beginning.

**Comment by danrabbit** [comment] 2022-01-20 20:05
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:05 UTC
