### ISSUE TITLE
Ratings don't work

### ISSUE THREAD

**Issue by jtrees** [elementary/music#86] opened 2017-11-15 08:32 UTC
#### Steps to Reproduce

1. Ensure you are in list view
2. Display the rating column
3. Right click on a track
4. Select a rating (stars)

#### Expected Result
The rating is displayed in the respective column

#### Actual Result
The rating doesn't change

#### Comments
I've tried various other ways to rate tracks such as directly clicking into the rating column or using the Edit Song Info dialog. None of them seem to have any effect.

**Comment by danrabbit** [comment] 2017-12-02 01:05
I'm going to close this as kind of a duplicate of #107 because it seems like we're going to remove star ratings from the app

**Closed by danrabbit** 2017-12-02 01:05 UTC
