### ISSUE TITLE
Audio CD problem!

### ISSUE THREAD

**Issue by whoppix70** [elementary/music#561] opened 2019-12-26 14:21 UTC
When I inaert a Audio CD the programm close himselve
(Dream Dance Best of 20 Years)

**Comment by 4jNsY6fCVqZv** [comment] 2019-12-26 14:45
Probably a duplicate of https://github.com/elementary/music/issues/437.
Can you start Music by typing "io.elementary.music" into your Terminal and show which error is displayed there when you try to mount the CD?

**Comment by 4jNsY6fCVqZv** [comment] 2019-12-26 14:46
Probably a duplicate of https://github.com/elementary/music/issues/437.

**Comment by whoppix70** [comment] 2019-12-28 10:44
** (io.elementary.music:2245): CRITICAL **: 11:42:02.713: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

(io.elementary.music:2245): GLib-GObject-CRITICAL **: 11:42:02.851: g_object_new_valist: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(io.elementary.music:2245): GLib-GObject-WARNING **: 11:42:02.852: cannot register existing type 'NoiseTreeViewSetup'

(io.elementary.music:2245): GLib-CRITICAL **: 11:42:02.852: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:2245): GLib-GObject-CRITICAL **: 11:42:02.852: g_object_new_valist: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Speicherzugriffsfehler

**Closed** 2020-04-22 17:31 UTC
