### ISSUE TITLE
Music's settings button doesn't use standard eOS popover

### ISSUE THREAD

**Issue by D0J0P** [elementary/music#661] opened 2021-08-31 21:59 UTC
## What Happened

Music's settings button doesn't use the HIG's popover style that every eOS app does, with the pointy end sticking out from the settings button. The animation it has when you click on it is not the same either.

## Expected Behavior

That the setting button popover would use elementary's HIG in style and animation. 

## Steps to Reproduce

1. Open Music and press the settings button
2. Open any other app and click it's setting button(other than Photos) or press anything on the wingpanel
3. Notice the style and animation are different

## Platform Information

Elementary OS 6 Odin

**Comment by cassidyjames** [comment] 2021-08-31 22:26
This is just a menu button which is perfectly fine according to the elementary HIG; the reason some other apps use a popover is when they contain more than just menu items. I wouldn't be opposed to moving to a popover here but it's not really necessary.

**Comment by danrabbit** [comment] 2022-01-20 20:18
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:18 UTC
