### ISSUE TITLE
Music does not detect changes to the file metadata

### ISSUE THREAD

**Issue by leo-unglaub** [elementary/music#698] opened 2022-02-24 14:19 UTC
### What Happened?

I used an external tool to edit the meta data (tags) of my music and the changes are not shown in Music itself. I restarted music a bunch of times, added items to the queue. Re-Imported music, ... . But the changes are still now shown.

### Steps to Reproduce

1. Open Music
2. Browse the library
3. Close Music
4. Use a third party tool to update the meta data
5. Open Music again <- Changes are not shown!

### Expected Behavior

Music should automatically (or after a manual re-scan) of the folder detect changes to the files and display them correctly.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danrabbit** [comment] 2022-02-25 22:48
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-02-25 22:48 UTC
