### ISSUE TITLE
Music not displaying metadata

### ISSUE THREAD

**Issue by Anvilator-web** [elementary/music#717] opened 2022-07-16 03:15 UTC
### What Happened?

I'm using elementaryOS 6.1 Jólnir

The Music App in eOS is unable to read data from Metadata of .mp3 files.
I've rechecked that the Metadata is written using VLC and Clementine, however, the Music app won't display the Metadata or anything.
I've tried restarting, reimporting songs into the library but it won't work

### Steps to Reproduce

1. Downloaded songs from mp3paw.com into Music Folder
2. Opened VLC
3. Entered Metadata Info such as Artist, Language, Album, etc.
4. Saved the Metadata
5. Rechecked that Metadata is written using Clementine
6. Opened Music from elementary 
7. Imported the songs from Music Library
8. Metadata is not being shown
9. Artist, Album, etc is being shown as unknown

### Expected Behavior

The Metadata information should be displayed in Music app

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

CPU: i5-2400 
RAM: 8GB DDR3
HDD: 1TB
SSD: 256GB

**Comment by danrabbit** [comment] 2022-07-28 19:13
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-07-28 19:13 UTC
