### ISSUE TITLE
make zeitgeist integration optional

### ISSUE THREAD

**Issue by decathorpe** [elementary/music#583] opened 2020-05-01 22:52 UTC
On fedora, there are only a few packages left that require zeitgeist, including Code (where it's optional), Files (not optional), Music (not optional), Slingthot (optional), and two other non-elementary packages. 

Would it be possible to make the zeitgeist integration in Music optional? It looks like zeitgeist is a pretty dead project, with only ~15 git commits in the three years since 2017's 1.0 release, and most of those are "only" compilation fixes by tintou and ricotz.

**Comment by danrabbit** [comment] 2020-10-09 18:01
I believe that currently Music relies on Zeitgeist for smart playlists. I know Corentin has been a proponent of using Tracked instead

**Comment by danrabbit** [comment] 2021-04-22 21:17
It looks like we're only using it for the history playlist. This would be automatically resolved by https://github.com/elementary/music/issues/630

**Comment by danrabbit** [comment] 2022-01-20 20:29
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:29 UTC
Labels: Priority: Wishlist

**Comment by decathorpe** [comment] 2022-01-20 21:07
Thanks for remembering the issue! I kind of already guessed, based on the work-in-progress screenshots you shared on twitter 👍🏼
