### ISSUE TITLE
Audio Metadata editor can't save the modified fields

### ISSUE THREAD

**Issue by sauntor** [elementary/music#726] opened 2022-10-01 18:54 UTC
### What Happened?

some metadata characters in the audio file has wrong encoding, so, I want edit it, but it does not save what I have modified, the metadata stays no change!

### Steps to Reproduce

1. install elemetary with chinese support
2. import some music into the io.elementary.music
3. edit some metadata, and click `Save`/`保存`
4. the fellow is a screen shot
![2022-10-02 02-46-24 的屏幕截图@2x](https://user-images.githubusercontent.com/2825145/193423905-a5f13403-c7e5-44b3-96e4-be8562e974e1.png)

### Expected Behavior

The `Title`、`Tracks` and other metadatas shown in the library or playlist list should change to what I input before

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

dell xps 15 9560, 4K touch screen with x2 scale

**Comment by danirabbit** [comment] 2022-10-12 16:34
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danirabbit** 2022-10-12 16:34 UTC
