### ISSUE TITLE
Add default title values to search feature

### ISSUE THREAD

**Issue by anddam** [elementary/music#48] opened 2017-07-13 14:05 UTC
Adding files without metadata will display the file name in the Title column, searching for music won't match any of these title default values.

If a field value is shown in the UI it should be searchable.

**Comment by danrabbit** [comment] 2022-01-20 19:56
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 19:56 UTC
