### ISSUE TITLE
Music views go blank and/or flicker

### ISSUE THREAD

**Issue by o-alquimista** [elementary/music#312] opened 2018-03-13 14:25 UTC
The _album view_ is practically blank all the time, while the _list view_ sometimes show something (albeit still glitching visually, like flickering) and the only view that works consistently is the _column view_.

noise version: 0.4.2+r2134-0+pkg102~ubuntu0.4.1.1
Upon running 'noise' through the terminal, it keeps printing a never-ending list of errors. [See here](https://gist.githubusercontent.com/o-alquimista/eafc44e8e72b56793380a6eda1beac41/raw/70089fa089e3dabbb5d8605d6c5441d05cde67dc/noise.txt).

![report-bug-noise-2](https://user-images.githubusercontent.com/25424263/37347564-dfe4e864-26b0-11e8-9946-c45b6821ac64.gif)

**Comment by o-alquimista** [comment] 2018-04-22 13:09
Unable to reproduce, along with [this bug](https://github.com/elementary/music/issues/311). It seems they are related.

**Comment by o-alquimista** [comment] 2018-10-10 01:29
Can reproduce this again. See [this.](https://github.com/elementary/music/issues/311#issuecomment-428406777)

**Comment by danrabbit** [comment] 2022-01-20 20:06
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:06 UTC
