### ISSUE TITLE
Difference between "Import Music" and "Change Music Folder" options?

### ISSUE THREAD

**Issue by casasfernando** [elementary/music#493] opened 2019-03-16 09:21 UTC
I searched for Music app docs but couldn't find any so decided to ask here.
Which is the difference between using the "Import Music" option and "Change Music Folder"?

Is import like a one time import task with no library refresh afterwards?

I simply want Music to add all my songs to the library and then add new songs when available (either manual trigger of a rescan or automatic periodic rescan). My music library is on a fileshare, is not small and it doesn't change so frequently so I don't mind triggering a manual rescan only when I add new items if that will prevent any unnecessary performance penalty.

**Comment by danrabbit** [comment] 2022-01-20 20:08
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:08 UTC
