### ISSUE TITLE
"noise_playback_manager_get_current_media: assertion failed" spamming onto my logs

### ISSUE THREAD

**Issue by o-alquimista** [elementary/music#505] opened 2019-05-13 00:41 UTC
My journalctl output is filling with these when I have noise/Music running:

```
mai 12 21:37:07 alq22 io.elementary.m[15759]: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
mai 12 21:37:07 alq22 io.elementary.m[15759]: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
mai 12 21:37:07 alq22 io.elementary.m[15759]: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
mai 12 21:37:07 alq22 io.elementary.m[15759]: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
mai 12 21:37:07 alq22 io.elementary.m[15759]: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
mai 12 21:37:07 alq22 io.elementary.m[15759]: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
mai 12 21:37:07 alq22 io.elementary.m[15759]: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
mai 12 21:37:07 alq22 io.elementary.m[15759]: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
mai 12 21:37:07 alq22 io.elementary.m[15759]: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
mai 12 21:37:08 alq22 io.elementary.m[15759]: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
mai 12 21:37:08 alq22 io.elementary.m[15759]: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
mai 12 21:37:08 alq22 io.elementary.m[15759]: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
mai 12 21:37:08 alq22 io.elementary.m[15759]: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
```

Running elementary Juno 5.0, fully updated, clean install.
I wonder if they could be related to issues #311 and/or #312 that I've reported. I can still reproduce them since Loki.

**Comment by asegarra** [comment] 2019-05-19 00:40
yeah same here, unfortunately this bug is at least over 1 year old.

**Comment by moqmar** [comment] 2020-09-20 14:35
Same on 6.0, I've got almost a quarter million lines in my log due to this bug, `journalctl` becomes quite unhelpful.
![grafik](https://user-images.githubusercontent.com/5559994/93713918-4ff2d280-fb5f-11ea-8710-68742b327646.png)

**Comment by vjr** [comment] 2020-09-20 16:01
I wanted to look into fixing this issue but I don't see the problem when I build from git master.

Also on odin, the music app release version seems to be 5.0.5 when there is at least 5.1.0 so not sure if that's relevant.

**Comment by jeremypw** [comment] 2020-09-21 08:46
I suspect this may be because the static PlaybackManager `App.player` is not being constructed in the `static construct` clause?  The error message suggest that one of its functions is being called before it has been constructed under some circumstances.

**Comment by vjr** [comment] 2020-09-21 08:51
Thanks! Yes that could be the cause but I am not able to reproduce the issue when I run my local build off master to be able to verify :-|

**Comment by jeremypw** [comment] 2020-09-21 15:39
I can now confirm that a clean install of the Music app from the 5.1 repository (version 5.0.5) does show this repeated warning.  I was previously testing with the daily version which seems to be OK.  Bisecting to locate commit responsible but probably #577

**Comment by jeremypw** [comment] 2020-09-21 16:36
Correction - I see that the Hera repository actually supplies version 5.0.4 although v 5.0.5 was released in March (??).

**Comment by danrabbit** [comment] 2022-01-20 20:17
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:17 UTC
