### ISSUE TITLE
The Music app is taking changes within the music library into account 

### ISSUE THREAD

**Issue by ralxxx** [elementary/music#590] opened 2020-08-02 18:12 UTC
**What is the current behavior?**

The MUSIC app is not syncing properly the music library.
- I have modified album covers but this has not been recognized by MUSIC. Neither after closing the app, nor after a reboot. 
- I have moved the album to a different location, I renamed the album folder and moved it back. Then, the album was scanned and could be played, but the music files from the album with the old folder names are still present in the music library and the album cover for none of the files has been updated in MUSIC.

 **What is the expected correct behavior?**
Ideally, MUSIC is taking notice  when changes in the music library happen (at least on restart of the app). The melody app from the AppCenter is doing this. As an alternative it would be fine as well to have a button in the settings menu that allows to activate a music library scan.

![141_elementary_music_screenshot](https://user-images.githubusercontent.com/36100882/89129287-764fa680-d4fc-11ea-84b3-16d8545ec153.png)

**Comment by danrabbit** [comment] 2022-01-20 20:21
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:21 UTC
