### ISSUE TITLE
Open and manage .m3u8 files (playlists)

### ISSUE THREAD

**Issue by katuak** [elementary/music#745] opened 2023-03-27 10:32 UTC
It would be useful to be able to open m3u8 files. Not like in eOS6 player where you could have them organized, but just add all of the songs to the queue would be enough.

**Comment by jeremypw** [comment] 2023-03-27 12:03
The solution to this could be similar to the one I suggested for opening music files except the FileChooser would have to filter on playlist files and after selecting one you would have to provide code to interpret the contents and convert it to an array of `GLib.File` objects before passing to the playback manager.

**Comment by aitor-gomila** [comment] 2023-03-27 12:25
So it's just a matter of parsing the file and passing it down to the playback manager. It can be done right now but I think it's dirty to just keep adding playlists on the same queue, so some thought needs to go on that.

At the same time I feel like the simplicity of Elementary's music player makes it special, so I don't really know what to do!

**Comment by jeremypw** [comment] 2023-03-27 16:40
Yes, you would probably need to clear the previous playlist when loading a new one (or allow the user to choose whether to or not). I am not sure how the UX team would feel about adding too many features to this app though as the intention was to slim it down compared with the previous version.

**Comment by aitor-gomila** [comment] 2023-03-27 17:43
Yes, I think the same. It should stay simple.

So TL;DR; opening .m3u8 files should be the same as opening a folder: add all files to the queue and that's it.

**Comment by BAProductions** [comment] 2023-03-28 11:05
Go back to using the eOS6 player instead

**Comment by aitor-gomila** [comment] 2023-04-06 19:47
Possible duplicate from 4 years ago #515

**Comment by aitor-gomila** [comment] 2023-04-22 13:01
Something along the lines of:
```javascript
// music will run this kind of handlers over and over until all of the files listed are readable by the program
// (e.g. no directories or m3u8)
// files not supported will be ignored and not added to queue
abstract class FileHandler {
  abstract string[] mimeType;
  string[] files();
}

class MP3Handler extends FileHandler { ... }

class M3U8Handler extends FileHandler {
  string[] mimeType = ["audio/x-mpeg-url"]
  // Returns absolute path to all songs
  string[] files() {
    // parse m3u8
    // return files in it
    return ["/home/foo/bar"];
  }
}
```

**Comment by danirabbit** [comment] 2023-08-30 16:44
Closing as a duplicate of #515

**Closed by danirabbit** 2023-08-30 16:44 UTC
