### ISSUE TITLE
Cannot update song information.

### ISSUE THREAD

**Issue by VA3DBJ** [elementary/music#451] opened 2018-10-27 14:09 UTC
Cannot update the song information.  Make changes to the title or anyother info, click save and reverts back to original imported info.  Does not save.

**Comment by Breakfast-for-Pigeons** [comment] 2018-10-27 15:43
I noticed the same problem. I didn't know if it was a new issue or related to an existing one, so described the issue here: https://github.com/elementary/music/issues/156

**Comment by SubhadeepJasu** [comment] 2018-11-01 17:31
@Breakfast-for-Pigeons  Its not the same issue. But yeah, I have the same problem too. Editing song data and hitting the save button does nothing.

**Comment by Breakfast-for-Pigeons** [comment] 2018-11-01 19:02
OK, thanks. I didn't want to open up a new issue if it was a duplicate.

**Comment by lecroix74** [comment] 2018-11-18 12:43
I can confirm the same issue here. it really is annoying. will have to install something else. but I still think this should work as it is a core app for the whole elementary. yet this is happening. and they say 'when it's ready'....

**Comment by Garalzus** [comment] 2019-01-11 17:31
Same issue. Please solve fast elementary :(

**Comment by aadilayub** [comment] 2019-03-13 09:18
I have also run in the issue. To illustrate: 

I edited this track:

![Screenshot from 2019-03-13 14 15 11](https://user-images.githubusercontent.com/31581044/54267135-86c75000-459a-11e9-93f6-b4db8eab7cb9.png)

Pressed the save button and the track remained unchanged:
![Screenshot from 2019-03-13 14 17 02](https://user-images.githubusercontent.com/31581044/54267260-be35fc80-459a-11e9-8117-ababd8388825.png)

The only thing that gets updated is album art.

**Comment by Mohelm97** [comment] 2019-03-13 10:13
@aadilayub What is the format of the song?

**Comment by aadilayub** [comment] 2019-03-13 10:46
> @aadilayub What is the format of the song?

Do you mean file format? It's an MP3

**Comment by DFergFLA** [comment] 2019-12-07 14:48
So, I have this problem too.  I saw it was reported in 2017 then in 2018 and now in 2019.  Just how many years is going to take for the developers to fix it instead of adding a new fancy feature

**Comment by aadilayub** [comment] 2019-12-08 06:32
@DFergFLA For what it's worth, this is a problem that persists in many music players on Linux. I have recently switched to GNOME and none of the music apps I've used there have functional metadata editing either. Also, I have read elsewhere that Music is a very old codebase and notoriously difficult to work with.

So that may provide some context as to why this bug has been unresolved all this time.

**Comment by SubhadeepJasu** [comment] 2019-12-08 07:00
May be I'll put in the functionality myself after I am done with my projects. I'll make a pull request.

**Comment by loaden** [comment] 2021-08-28 15:24
Audacious can edit the song info well.

**Comment by danrabbit** [comment] 2022-01-20 20:10
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:10 UTC
