### ISSUE TITLE
Possibility to rearrange order of tracks in playlist missing

### ISSUE THREAD

**Issue by Heiko-M** [elementary/music#61] opened 2017-09-02 14:46 UTC
I think it's an important feature to be able to come back to a playlist and change the order in which the tracks are played. I could not find a way to do this so far, except the tedious rebuilding of the whole playlist from scratch.

**Comment by danrabbit** [comment] 2022-01-20 19:57
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 19:57 UTC
