### ISSUE TITLE
Repeated crashes on importing from default music directory

### ISSUE THREAD

**Issue by chrisandrew-dev** [elementary/music#595] opened 2020-08-22 22:21 UTC
Total files approx. 4000,
Total files approx. 390,
App is unresponsive and hangs during import and scanning resulting in frequent crashes,
CPU utilisation sits around 30-50% with process running,
RAM utilisation sits around 200MB for Music,

OS:
5.1.7 Hera clean install with system updates installed.

Hardware:
Lenovo ideapad-320 14IAP
8GB 
Pentium N4200 Quad-core

**Comment by danrabbit** [comment] 2022-01-20 20:21
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:21 UTC
