### ISSUE TITLE
Plugin development documentation

### ISSUE THREAD

**Issue by kosmynin** [elementary/music#566] opened 2020-02-02 22:20 UTC
Is there any documentation on the plugin infrastructure? Specifically I am looking for a more detailed description of the interface and some guidelines and/or examples on file structure etc.

**Comment by danrabbit** [comment] 2022-01-20 20:16
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:16 UTC
