### ISSUE TITLE
There is a bug when you try install Music app: "The package id's '' are not valid"

### ISSUE THREAD

**Issue by dneutrino** [elementary/music#581] opened 2020-04-12 23:43 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

If applicable, add screenshots or screen recordings to help explain your problem.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by danrabbit** [comment] 2020-04-12 23:53
Please fill out the issue template. It is very difficult to find the source of the issue unless  you provide steps to reproduce the issue

**Comment by dneutrino** [comment] 2020-04-13 10:58
Firstly I loose my standart Music app icon, but app worked.Then I uninstall it, and try to reinstall, but get this issu. Cant install and see this, what is on screenshoot.
![1586775424426](https://user-images.githubusercontent.com/49293551/79115517-b85aae00-7d8e-11ea-83a4-22cab6fdce18.jpg)
And I slill have 5.1.2 not 5.1.3
![1586775501061](https://user-images.githubusercontent.com/49293551/79115567-dcb68a80-7d8e-11ea-8709-1ad203c17867.jpg)

**Comment by danrabbit** [comment] 2022-01-20 20:17
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:17 UTC
