### ISSUE TITLE
Scans music library every single time I run it

### ISSUE THREAD

**Issue by o-alquimista** [elementary/music#311] opened 2018-03-13 09:50 UTC
It forces the lengthy process of scanning the music folder on every startup of the application. I expect to be able to listen to music when I launch it, but now I have to wait for it to scan first.

noise version: **0.4.2+r2134-0+pkg102~ubuntu0.4.1.1**
Upon running 'noise' through the terminal, it keeps printing a never-ending list of errors. See [here](https://gist.githubusercontent.com/o-alquimista/eafc44e8e72b56793380a6eda1beac41/raw/70089fa089e3dabbb5d8605d6c5441d05cde67dc/noise.txt).

![report-noise-bug](https://user-images.githubusercontent.com/25424263/37334396-8876d338-268a-11e8-8668-51bf61e80de0.png)

**Comment by BaptisteGelez** [comment] 2018-03-13 12:36
I can't reproduce on my computer, but running `rm ~/.local/share/noise/*.db`, an then restarting Music may help.

**Comment by o-alquimista** [comment] 2018-03-13 14:35
OK, deleted the database. Upon starting it, noise scans my music and finishes successfully. I close noise and reopen it. It begins to scan for music again.

**Comment by BaptisteGelez** [comment] 2018-03-13 16:30
Can you please post the list of your music files (with `tree ~/Music` for instance)?

**Comment by o-alquimista** [comment] 2018-03-13 21:17
Here: https://gist.github.com/o-alquimista/f2b46ef06d214e89e16812857b4f05d3

**Comment by artemanufrij** [comment] 2018-03-14 00:16
@o-alquimista could you test your library on Melody please? Just for a feedback

https://appcenter.elementary.io/com.github.artemanufrij.playmymusic

**Comment by o-alquimista** [comment] 2018-03-14 01:51
Yes, Melody works as expected. It's bug-free for me.

![captura de tela de 2018-03-13 22 49 38](https://user-images.githubusercontent.com/25424263/37379105-d5fbf2ec-2710-11e8-9dfa-387baf24892c.png)

**Comment by artemanufrij** [comment] 2018-03-14 06:19
Thanks for feedback

**Comment by o-alquimista** [comment] 2018-04-06 23:16
I don't know if anyone noticed, but my music library is entirely composed of .ogg files. I will try to create a small library of .mp3 files and inform you of the result.

**Comment by o-alquimista** [comment] 2018-04-22 13:07
For the first time, I am unable to reproduce this. Also, [this bug](https://github.com/elementary/music/issues/312) is also gone.

Noise version: 0.4.2+r2134-0+pkg102~ubuntu0.4.1.1

**Comment by o-alquimista** [comment] 2018-10-10 01:27
Can reproduce this again, including #312 (fresh install, all updates installed, same music collection) 
0.4.2+r2134-0+pkg102~ubuntu0.4.1.1

**Comment by o-alquimista** [comment] 2018-10-19 19:07
Affects elementary Juno 5.0 too. Hello?

**Comment by o-alquimista** [comment] 2019-03-15 10:42
I placed 2 folders with a few .mp3 files in my Music folder for testing. On startup, the scan happened anyway, and repeated subsequent startups. Obviously, it was faster, but I suppose with a larger library it is slow.

**Comment by jeremypw** [comment] 2020-09-26 08:46
If you have music files that Music cannot play it will generate errors in the terminal and also Music keeps trying to add them everytime it starts (it thinks they are newly added music files).  Try adding the bad and maybe the ugly set of gstreamer plugins.  See #604 for a PR that attempts to ameliorate this.  Might be worth having a setting to turn off the automatic scanning of the library folder for new files though.

**Comment by dennismayr** [comment] 2021-09-09 20:25
Also, in the process, it will take up all available RAM and swap (13Gb).

**Comment by diogopessoa** [comment] 2021-09-30 10:43
I'm using Odin and still the same problem. I will share some more information:

![Captura de tela de 2021-09-30 07-11-20](https://user-images.githubusercontent.com/12633864/135439198-149cd78e-c2ee-4efa-bb33-32f7c8adaa18.png)
![Captura de tela de 2021-09-30 07-12-18](https://user-images.githubusercontent.com/12633864/135439226-237ec5bc-459b-48bf-8eae-08e9837eff24.png)
![Captura de tela de 2021-09-30 07-11-49](https://user-images.githubusercontent.com/12633864/135439210-222bee39-e7cd-4f64-a17e-2e16ce1bfe02.png)
My music library is entirely .mp3 files.

**Comment by danrabbit** [comment] 2022-01-20 20:06
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:06 UTC
