### ISSUE TITLE
In Grid view scale canvas to album art

### ISSUE THREAD

**Issue by AI-ien** [elementary/music#664] opened 2021-09-29 11:47 UTC
## Problem
In grid view album art is placed in fixed size 1:1 rectangle. If album image is not precisely 1:1 aspect ratio it will be pulled to top left corner leaving underlying blank placeholder image visible.

## Proposal
To make it more visually appealing I would propose to dynamically scale underlying placeholder image to album image art size and maybe also adding subtle border around it. An example would be something what gnome-music have done.

**Default Music app**
![Screenshot from 2021-09-29 14 10 24](https://user-images.githubusercontent.com/33252703/135261979-eb055413-706b-446a-a68c-fbe692fc1167.png)
**Gnome music app**
![Screenshot from 2021-09-29 14 46 25](https://user-images.githubusercontent.com/33252703/135262296-72aa8351-ce00-4e43-afc2-e07ed4fdcf42.png)

**Comment by danrabbit** [comment] 2022-01-20 20:22
Duplicate of #441

**Closed by danrabbit** 2022-01-20 20:22 UTC
