### ISSUE TITLE
Dead slow when many songs in the library

### ISSUE THREAD

**Issue by CosminIonascuZippie** [elementary/music#502] opened 2019-04-23 09:06 UTC
I have about 10.000 mp3s in my music folder and with this amount of files the app is dead slow. Takes at least 15 seconds to start it and complete the folder rescan. Then every mp3 search in the search field takes 1-2 seconds.

The main problem with the app seems to be the fact that all the search and background operations are being done on the GUI thread and when anything is performed, the GUI freezes until the operation is completed. While this might not be a big issue on under 1000 songs library, the app becomes unusable on 10.000+ songs libraries.

Worth mentioning that the performance issues I experince are on a 2018-built Dell XPS 15 Intel® Core™ i7-8750H CPU @ 2.20GHz hexacore with 16 GB of RAM and Elementary OS JUNO.

**Comment by benjaminky** [comment] 2019-05-27 09:41
Your processor is very strong, I think it's slow when many songs [ringtone MP3](https://freeringtonesmobile.net) in the playlist are due to software on your computer

**Comment by danrabbit** [comment] 2022-01-20 20:17
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:17 UTC
