### ISSUE TITLE
If delete a track from folder Music, then app is crashed.

### ISSUE THREAD

**Issue by pavlov24** [elementary/music#401] opened 2018-08-03 20:59 UTC
App is playing a track. When I am deleting other track from folder Music through file manager, app is crashing.

**Comment by danrabbit** [comment] 2022-01-20 20:05
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:05 UTC
