### ISSUE TITLE
Fails to build with stricter type-argument checking of valac

### ISSUE THREAD

**Issue by ricotz** [elementary/music#454] opened 2018-11-06 17:53 UTC
```vala
../src/Views/Wrappers/MusicViewWrapper.vala:67.9-67.50: error: Assignment: Cannot convert from `Gee.HashMap<Noise.Device,int>' to `Gee.HashMap<weak Noise.Device,int>'
        _devices = new Gee.HashMap<Device, int> ();
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
See https://gitlab.gnome.org/GNOME/vala/issues/696

**Comment by danrabbit** [comment] 2022-01-20 20:10
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:10 UTC
