### ISSUE TITLE
Fix smart playlist presets.

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#157] opened 2017-12-04 12:46 UTC
we need some new ones.

**Comment by Bat41** [comment] 2017-12-04 20:04
Can you give examples of presets you would like to see by default? Or what is wrong with the present ones?

**Comment by danrabbit** [comment] 2022-01-20 20:00
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:00 UTC
