### ISSUE TITLE
Music player does not play any music

### ISSUE THREAD

**Issue by ghost** [elementary/music#665] opened 2021-10-20 12:05 UTC
### What Happened?

When I first installed Elementary OS 6 a few days ago, everything was fine. I could play every music file I wanted but now it does not play. By _doesn't play_ I mean it doesn't give any voice, but it looks like it is playing. Below, I will give you the terminal output.

### What I tried so far

I tried wiping the ~local/share/noise folder but the result is the same.

### Steps to Reproduce

No idea if it's reproducible bug.

### Expected Behavior

It needs to play songs with actual output.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
~$ io.elementary.music

(io.elementary.music:6826): GLib-GObject-CRITICAL **: 14:57:27.063: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:6826): GLib-GObject-CRITICAL **: 14:57:27.091: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:6826): GLib-GObject-CRITICAL **: 14:57:27.170: Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type 'GeeBidirSortedSet' of the property on the interface 'GeeBidirSortedSet'

** Message: 14:57:27.553: iPod.vala:37: Activating iPod Device plugin
** Message: 14:57:27.553: AudioPlayer.vala:37: Activating AudioPlayer Device plugin

** (io.elementary.music:6826): CRITICAL **: 14:57:27.554: music_playback_manager_add_playback: assertion 'self != NULL' failed

** (io.elementary.music:6826): CRITICAL **: 14:57:27.806: music_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:6826): CRITICAL **: 14:57:27.807: music_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:6826): CRITICAL **: 14:57:28.384: music_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:6826): CRITICAL **: 14:57:28.384: music_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:6826): CRITICAL **: 14:57:28.585: music_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:6826): CRITICAL **: 14:57:28.585: music_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:6826): CRITICAL **: 14:57:28.786: music_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:6826): CRITICAL **: 14:57:28.786: music_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:6826): CRITICAL **: 14:57:28.986: music_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:6826): CRITICAL **: 14:57:28.986: music_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:6826): CRITICAL **: 14:57:29.186: music_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:6826): CRITICAL **: 14:57:29.186: music_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:6826): CRITICAL **: 14:57:29.387: music_playback_manager_get_current_media: assertion 'self != NULL' failed
```

**Comment by rakshit087** [comment] 2021-11-02 08:10
Is sound in your system working fine?

**Comment by danrabbit** [comment] 2022-01-20 20:20
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:20 UTC
