### ISSUE TITLE
Incorrect track order in album view when a track has multiple artists

### ISSUE THREAD

**Issue by 413Michele** [elementary/music#73] opened 2017-09-20 21:20 UTC
When tracks in the same album have different "artist" tags (such as multiple authors for a single song), tracks are ordered first from the "artist" tag and only then from the "track" tag as they should.
As far as i can tell, this only happens in the album view, in the others the correct order is respected.

The artist tag in the problematic files is written like this:
`artist1\\artist2`
which is surely recognized by Music, because in the list view the Artist column divide them with a comma.

Here is an example of expected and actual behaviour:

![expected](https://user-images.githubusercontent.com/29912185/30667922-63037372-9e59-11e7-9e08-0f7eb70dd86f.png)

![actual](https://user-images.githubusercontent.com/29912185/30667930-6ac1cef6-9e59-11e7-9421-9c64075f8d57.png)

(note that in Album view you actually view just the title of the song)

**Comment by Nine-H** [comment] 2018-12-04 06:10
Hello, I spent this afternoon trying to fix this one, as far as I can tell it's because the SQL we're using is:

```
SELECT
    `track`, `artist`, `album`
FROM
    `media`
ORDER BY
    `artist` ASC, `album`, `track`
```

but this is naieve artist sort, what we actually want is:

```
SELECT
    `track`, `artist`, `album`
FROM (
    SELECT
        COALESCE(NULLIF(`album_artist`,''), `artist`) as sort_artist, *
    FROM
        `media`
    ORDER BY
        sort_artist ASC, `album`, `track`
)
```

but I'm f**** terrible at vala, so it's going to take a little bit for me to make a patch. sit tight.

**Comment by Nine-H** [comment] 2018-12-04 06:14
but obv. this isn't gonna help if the metadata sucks.

**Comment by danrabbit** [comment] 2022-01-20 19:57
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 19:57 UTC
