### ISSUE TITLE
Pressing Enter on playing item has unexpected effects.

### ISSUE THREAD

**Issue by jeremypw** [elementary/music#536] opened 2019-09-13 16:30 UTC
The Enter key causes the selected item to play if it is not currently playing (expected).  However, pressing it again does not pause/stop the playback.  Moreover, if the the key is held down for more than a very short time, a visual glitch appears in the progress bar.  If it is held down longer, strange numbers appear for the length and current position.

**Comment by kgrubb** [comment] 2019-09-15 14:57
Here's what it looks like:

In the following gif, I first use `Enter` to start a song, then I select another song and long-press the `Enter` button.
![ezgif com-optimize](https://user-images.githubusercontent.com/8471701/64923374-670e2000-d7a7-11e9-9f8d-ffe09f69c70f.gif)

**Comment by danrabbit** [comment] 2022-01-20 20:15
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:15 UTC
Labels: Status: Confirmed
