### ISSUE TITLE
Take the filename as default song info when no available and editing

### ISSUE THREAD

**Issue by AlexFBP** [elementary/music#79] opened 2017-10-28 19:37 UTC
When a song in the library appears to not have information, appears the filename, but when going to write the full information, i have to go to the folder of the song, and copy the filename, to start splitting it and fill the fields, it would be better if at least the filename loads up (when opening the editor of song information - idk how appears in English, i have spanish version) on the first field, to avoid open the folder and copy the name
![image](https://user-images.githubusercontent.com/6588872/32137868-96c6629e-bbed-11e7-934a-83c4a2e0bdb5.png)

**Comment by danrabbit** [comment] 2022-01-20 20:01
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:01 UTC
