### ISSUE TITLE
Rescan everytime I close music

### ISSUE THREAD

**Issue by tatiee** [elementary/music#670] opened 2021-11-27 17:57 UTC
### What Happened?

Not sure if this is supposed to happen, but whenever I close and reopen music it goes through a whole rescan. Kinda frustrating. My music library is on a separate disk (SSD vs the HDD elementary is located) so if that's the reason so be it.

### Steps to Reproduce

1. Close music
2. Reopen
3. Music scan restarts all over

### Expected Behavior

Music should just stay put in the app.

### OS Version

5.x (Hera)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment] 2021-11-27 18:42
Is it related to the "Keep Music Folder Organised" preference setting?

**Comment by kevinwithat** [comment] 2021-11-27 19:03
I just tried toggling it off, closing music, and it's now "rescanning music for changes" again. It's not the worse thing in the world (I don't have a huge library) but I feel like something is off...

**Comment by jeremypw** [comment] 2021-11-28 10:00
I've now had a look at the code and it seems that the folder is always rescanned when the app is launched.  I guess the idea is that while the app was closed, new music files may have been added to the folder or some have been removed by another process.  The rescan function is asynchronous so should not block the interface (if it does seriously impact the UX then that is an issue)

**Comment by kevinwithat** [comment] 2021-11-28 13:04
Ah that makes sense. It doesn’t effect anything else so that’s good - just takes awhile since I’m running this on a slow HDD. Thanks for your help!

**Comment by 69graves** [comment] 2022-01-11 15:44
> I've now had a look at the code and it seems that the folder is always rescanned when the app is launched.  I guess the idea is that while the app was closed, new music files may have been added to the folder or some have been removed by another process so the database may need to be updated.  The rescan function is asynchronous so should not block the interface (if it does seriously impact the UX then that is an issue)

Ugh, seriously?   It's a beautiful looking app, but this automatic everything needs to stop!

**Comment by danrabbit** [comment] 2022-01-20 20:18
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:18 UTC
