### ISSUE TITLE
Notification (track change) always plays sound, despite setting

### ISSUE THREAD

**Issue by jtrees** [elementary/music#74] opened 2017-10-03 15:55 UTC
### Steps to Reproduce

1. Navigate to System Settings --> Notifcations --> Music
2. Turn Bubbles and Notification Center on.
3. Turn off Sounds.
4. Listen to music with the app.
5. Ensure your focus is on another app.
6. Wait for the next track.

### Expected Result

No sound.

### Actual Result

A sound plays.

**Comment by davidmhewitt** [comment] 2017-10-11 22:45
I am not able to reproduce this issue. Can you confirm whether or not this happens with other applications if you disable the sound for their notifications in the settings?

**Comment by jtrees** [comment] 2017-10-12 08:54
Thanks for the suggestion. It does indeed seem to be a general issue. I just tried turning off the sound for Mail notifications but that also had no effect. Shall I create an issue on a different tracker? If so, which one?

**Comment by danrabbit** [comment] 2022-01-20 19:58
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 19:58 UTC
