### ISSUE TITLE
App crashing when mounting an ext4 partition

### ISSUE THREAD

**Issue by r0manr0k0n** [elementary/music#574] opened 2020-02-29 14:56 UTC
When mounting only that partition the music app crashes then not opening anymore.
This app has nothing to do with that partition.
My music library is in another partition which is a ntfs partition.

**Terminal Output:**

```
(io.elementary.music:17941): GLib-GObject-CRITICAL **: 20:45:14.482: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:17941): GLib-GObject-CRITICAL **: 20:45:14.591: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:17941): GLib-GObject-CRITICAL **: 20:45:14.932: Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type 'GeeBidirSortedSet' of the property on the interface 'GeeBidirSortedSet'


(io.elementary.music:17941): GLib-GObject-WARNING **: 20:45:15.233: cannot register existing type 'NoiseViewWrapper'

(io.elementary.music:17941): GLib-CRITICAL **: 20:45:15.233: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:17941): GLib-GObject-CRITICAL **: 20:45:15.233: g_type_register_dynamic: assertion 'parent_type > 0' failed
** Message: 20:45:15.243: iPod.vala:37: Activating iPod Device plugin
** Message: 20:45:15.243: CDRom.vala:37: Activating CD-Rom Device plugin
** Message: 20:45:15.243: AudioPlayer.vala:37: Activating AudioPlayer Device plugin
** Message: 20:45:15.243: LastFM.vala:42: Activating Last.fm plugin

** (io.elementary.music:17941): CRITICAL **: 20:45:15.244: noise_playback_manager_add_playback: assertion 'self != NULL' failed

(io.elementary.music:17941): GLib-GObject-WARNING **: 20:45:15.245: invalid (NULL) pointer instance

(io.elementary.music:17941): GLib-GObject-CRITICAL **: 20:45:15.245: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(io.elementary.music:17941): GLib-GObject-WARNING **: 20:45:15.245: invalid (NULL) pointer instance

(io.elementary.music:17941): GLib-GObject-CRITICAL **: 20:45:15.245: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(io.elementary.music:17941): GLib-GObject-WARNING **: 20:45:15.245: invalid (NULL) pointer instance

(io.elementary.music:17941): GLib-GObject-CRITICAL **: 20:45:15.245: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(io.elementary.music:17941): GLib-GObject-WARNING **: 20:45:15.366: cannot register existing type 'NoiseGStreamerTagger'

(io.elementary.music:17941): GLib-CRITICAL **: 20:45:15.366: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:17941): GLib-GObject-CRITICAL **: 20:45:15.366: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault
```

*sorry for my poor english

**Comment by rokonxr** [comment] 2020-04-29 11:37
I've figured it out! There was too many levels of symbolic links in that partition. I delete those symbolic links and it is now working. 
It seems like the music player always scanning the whole drive(not partition) rather than the selected location.

**Comment by danielqba** [comment] 2021-08-08 01:34
So, this is not going to get fixed? The same happens to me!

**Comment by danrabbit** [comment] 2022-01-20 20:16
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:16 UTC
