### ISSUE TITLE
Clean up Edit Song Info dialog action area spacing

### ISSUE THREAD

**Issue by cassidyjames** [elementary/music#621] opened 2021-02-08 20:25 UTC
![Screenshot from 2021-02-08 13-25-02](https://user-images.githubusercontent.com/611168/107277002-0f61fb80-6a11-11eb-8aeb-92f20322cd76.png)

**Comment by danrabbit** [comment] 2022-01-20 20:20
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:20 UTC
