### ISSUE TITLE
Crashes on Launch

### ISSUE THREAD

**Issue by StanfordRahl** [elementary/music#565] opened 2020-01-09 17:54 UTC
The app worked fine in the live boot, but after installing it never ran. The window basically flashes and closes. It's crashing on launch

**Comment by ghabit** [comment] 2020-01-11 10:05
@StanfordRahl do you have ntfs mounted partition? Is your user in plugdev group?

**Comment by matiyin** [comment] 2020-02-21 16:28
I have the same issue, and have a bitlocker mounted partition. I'm sure I've seen it open after I installed eOS, but now I want to use it it doesn't start anymore. Let me know if I should send any logs, if there are any.

**Comment by themightyoarfish** [comment] 2020-03-28 15:30
For me it also segfaults:
```
(lldb) run
Process 18732 launched: '/usr/bin/io.elementary.music' (x86_64)

(io.elementary.music:18732): GLib-GObject-CRITICAL **: 16:30:29.100: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:18732): GLib-GObject-CRITICAL **: 16:30:29.116: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:18732): GLib-GObject-CRITICAL **: 16:30:29.174: Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type 'GeeBidirSortedSet' of the property on the interface 'GeeBidirSortedSet'


(io.elementary.music:18732): GLib-GObject-WARNING **: 16:30:29.419: cannot register existing type 'NoiseViewWrapper'

(io.elementary.music:18732): GLib-CRITICAL **: 16:30:29.419: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:18732): GLib-GObject-CRITICAL **: 16:30:29.419: g_type_register_dynamic: assertion 'parent_type > 0' failed
** Message: 16:30:29.419: LastFM.vala:42: Activating Last.fm plugin
** Message: 16:30:29.419: AudioPlayer.vala:37: Activating AudioPlayer Device plugin
** Message: 16:30:29.419: iPod.vala:37: Activating iPod Device plugin
** Message: 16:30:29.419: CDRom.vala:37: Activating CD-Rom Device plugin

** (io.elementary.music:18732): CRITICAL **: 16:30:29.421: noise_playback_manager_add_playback: assertion 'self != NULL' failed

** (io.elementary.music:18732): CRITICAL **: 16:30:29.629: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:18732): CRITICAL **: 16:30:29.629: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

(io.elementary.music:18732): GLib-GObject-WARNING **: 16:30:29.632: cannot register existing type 'NoiseGStreamerTagger'

(io.elementary.music:18732): GLib-CRITICAL **: 16:30:29.632: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:18732): GLib-GObject-CRITICAL **: 16:30:29.632: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Process 18732 stopped
* thread #1, name = 'io.elementary.m', stop reason = signal SIGSEGV: invalid address (fault address: 0x18)
    frame #0: 0x00007fff8f7e7730 libaudioplayer-device.so`noise_gstreamer_tagger_construct + 416
libaudioplayer-device.so`noise_gstreamer_tagger_construct:
->  0x7fff8f7e7730 <+416>: movq   0x18(%rax), %rax
    0x7fff8f7e7734 <+420>: movq   0x20(%rax), %rdi
    0x7fff8f7e7738 <+424>: testq  %rdi, %rdi
    0x7fff8f7e773b <+427>: je     0x7fff8f7e774e            ; <+446>
(lldb) 
```

**Comment by StanfordRahl** [comment] 2020-03-28 16:23
> @StanfordRahl do you have ntfs mounted partition? Is your user in plugdev group?

He there, I don't even know how this went past me the entire time. I managed to locate the cause of the problem. Mounting the NTFS causes the problem. If I unmount I can launch Music without a problem. If Music is open and then I remount the partition it'll close immediately. 

I had thought that my mounting point was the problem but it's not in the media directory so I don't know how the two could be related...

**Comment by BAProductions** [comment] 2021-09-10 12:13
Won't open for me sometimes even if i compile it me self

**Comment by danrabbit** [comment] 2022-01-20 20:16
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:16 UTC
