### ISSUE TITLE
Application name appearing under Gnome

### ISSUE THREAD

**Issue by ilippert** [elementary/music#639] opened 2021-06-01 08:49 UTC
I run Music on Fedora34, happily.

## What Happened

This is about the interaction with https://extensions.gnome.org/extension/3499/application-volume-mixer/ - that extension gets from many application a correct name of the Application.
Music, however, seems to share `io.elementary.music` with its environment as its name.

## Expected Behavior

Music should identify itself as `Music`.

## Steps to Reproduce

1. install & activate the extension on a Gnome-compatible system
2. run Music
3. find  `io.elementary.music` as the name. 

## Platform Information
* Fedora 34
* Music 5.1.0, updated 24/05/21

**Comment by danrabbit** [comment] 2022-01-20 20:20
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:20 UTC
