### ISSUE TITLE
Missing "View in Columns" button icon when installed on other Linux Distros.

### ISSUE THREAD

**Issue by Breakfast-for-Pigeons** [elementary/music#450] opened 2018-10-27 07:18 UTC
After installing Music/Noise on other Linux distros ( I tried it on Ubuntu Bionic Beaver and Linux Mint 19)...

```
sudo add-apt-repository ppa:elementary-os/stable
sudo apt-get update
sudo apt-get install noise
```
... the icon/graphic for the "View in Columns" button is missing. It just displays a circle with a line through it.

![music_on_ubuntu](https://user-images.githubusercontent.com/13591438/47600928-43bf6400-d98e-11e8-94cb-4a8cb14a7a5e.png)

**Comment by danrabbit** [comment] 2022-01-20 20:10
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:10 UTC
