### ISSUE TITLE
Library List View should save sort settings

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#68] opened 2017-09-06 08:47 UTC
Sorting in list view is broken. When you cold start the app it sorts by artist descending (z-a), then you have to click the artist column header twice: once to get the sorting order and the column header in sync and once to set the sorting back to artist ascending (a-z).

(a patch getting it to start in ascending (a-z) would also be acceptable)

**Comment by danrabbit** [comment] 2022-01-20 19:57
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 19:57 UTC
