### ISSUE TITLE
Music App constantly crashes with large music library

### ISSUE THREAD

**Issue by PompeiiHi** [elementary/music#649] opened 2021-08-14 14:22 UTC
For context my music library is just over 300GB with just over 8000 FLAC files. The default music application that comes with elementary os 6.0 constantly crashes and/or freezes when attempting to open or while scanning a large music library. This appears to be an issue with the app itself and not some process that eOS is using to handle music files because there is no issue with rhythmbox or tauon music box.

**Comment by danrabbit** [comment] 2022-01-20 20:18
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:18 UTC
