### ISSUE TITLE
Maximized window doesn't have rounded corners at the top like other eOS apps do. 

### ISSUE THREAD

**Issue by D0J0P** [elementary/music#297] opened 2018-02-24 01:46 UTC
Instead, the corners are squared off.

**Comment by aljelly** [comment] 2018-04-26 13:00
The corners for Music when maximised are rounded for me. elementary OS Loki, Music (daily build).

**Comment by D0J0P** [comment] 2018-04-26 13:56
I'm not on the daily build, just the standard Loki.

**Comment by danrabbit** [comment] 2018-06-15 22:08
I'm going to close this as "Incomplete" since I can't reproduce this in master

**Closed by danrabbit** 2018-06-15 22:08 UTC

**Comment by aadilayub** [comment] 2018-08-27 16:29
(sorry for the "me too" comment) just wanted to add that music has always been square for me when maximized since i started using loki months ago

![image](https://user-images.githubusercontent.com/31581044/44671881-474f7100-aa59-11e8-848a-b76880eee5b6.png)
