### ISSUE TITLE
Impossible to use

### ISSUE THREAD

**Issue by grmain** [elementary/music#553] opened 2019-10-26 13:34 UTC
Music never succeeded to import my music folder (around 10 000 files): very slow at the beginning, then systematic crashed.

**Comment by maboleth** [comment] 2019-12-17 11:04
Yep and you know what? Nobody cares. :) You reported this issue in October and nobody from devs/mods even dared to reply you back.

Currently, Noise/Music is an abomination of an app that needs 50min to load +6500 mp3 and flac files. 
It's beyond me how devs envisioned the music app that plays your music files **when import simply does not work.** What did you expect? A hundred or so files in our libraries? In 2020? Seriously?

**Comment by grmain** [comment] 2019-12-17 11:37
Ha ha ha!
Maybe some people, many, don't have that much music files and prefer streaming through Spotify, I'd be curious about the habits.
Music is indeed an abominationof an app, and many other applications that come with the OS too. I replaced almost all of them, exception made for Pantheon Mail (which doesn't work very well either) and Pantheon Files.
That is the major grievance I'll make to elementary OS: the team wants their OS to be a little like MacOS, and to be honest that's interesting because you install your OS, log in, have a pre-installed and sexy ready to use software bundle, AND some reviewed and curated selection of apps in the software center. For people who want a system to be intuitive and may get afraid putting hands upon Terminal, that's a cool philosophy.
In practice, I get angry pretty often. When you install some piece of software that hasn't been reviewed, you get a warning "oh là là, it may be dangerous, be careful my friend, please trust our reviewed apps instead". The fact is I have a really nice user experience with eOS having chosen Lollypop, Shotwell, Firefox/Vivaldi, MPV over the pre-installed and curated apps. They actually work, it's my user-experience-based reviewing software policy, and it occurs to be more reliable than the warning dialogs I receive, which are, and that's the point I wanted to stress, embarrassing for this Apple-like policy. One can blame Apple for maaaaany things, I'll be the first one to throw rocks at them, but their apps work. I don't like them, but they work.

But eOS is cool, I don't have the intention to change, it's really a cool OS to use. Just. I don't know. I would like to see them be less Apple-ish in the way they lock software installation and customization.

**Comment by vjr** [comment] 2019-12-17 11:54
Can you mention if you also have a lot of subdirectories in your music folder collection? I am thinking about looking into this issue to see if I can help fix it but no promises :-)

**Comment by grmain** [comment] 2019-12-17 12:04
Hi Vishal!
Here are my folder's properties.
![image](https://user-images.githubusercontent.com/57038387/70993846-2f2bb700-20cd-11ea-84fd-ca289b8e978e.png)
All my folders are structured this way: /artist/album/
![image](https://user-images.githubusercontent.com/57038387/70994068-aa8d6880-20cd-11ea-804c-7dea55aaa751.png)

**Comment by maboleth** [comment] 2019-12-17 17:51
Your words are like my own, like I have copy pasted my issues that I have with eOS. We even use the same alternative programs. :)

It just proves that people (users) know what they like, what does the job and what doesn't, while linux devs live in their own little cloud, egos, ideas, visions, whatever, but it's not aligned with the usability and what others need. 
Majority of users won't even write any reports but will quit it altogether when they see that certain app is not meeting their own expectations. Meanwhile devs will polish some trivial stuff in their own abomination, without ever realizing why not many people are using it in the first place, why are people migrating and opting for "unsafe" alternatives.

And why should they stay when support/mods/devs don't ever reply back? Or fix issues. People, like yourself, invest their own time explaining the bugs. To whom? I've seen one guy reported Noise import issue this March, or was it May? Nobody ever replied back. Do they really think people will wait forever for them to fix the most basic and integral stuff? 

it's not only eOS. I've seen many image programs in linux that suffer similar issues. As a professional photographer I could write books about missed opportunities, wrong UIs etc. But it's what it is and I'm sad to say that most of my Linux endeavours end with deleting the ext4 partitions, dual-boots and going back to Win for good.


> 
> 
> Ha ha ha!
> Maybe some people, many, don't have that much music files and prefer streaming through Spotify, I'd be curious about the habits.
> Music is indeed an abominationof an app, and many other applications that come with the OS too. I replaced almost all of them, exception made for Pantheon Mail (which doesn't work very well either) and Pantheon Files.
> That is the major grievance I'll make to elementary OS: the team wants their OS to be a little like MacOS, and to be honest that's interesting because you install your OS, log in, have a pre-installed and sexy ready to use software bundle, AND some reviewed and curated selection of apps in the software center. For people who want a system to be intuitive and may get afraid putting hands upon Terminal, that's a cool philosophy.
> In practice, I get angry pretty often. When you install some piece of software that hasn't been reviewed, you get a warning "oh là là, it may be dangerous, be careful my friend, please trust our reviewed apps instead". The fact is I have a really nice user experience with eOS having chosen Lollypop, Shotwell, Firefox/Vivaldi, MPV over the pre-installed and curated apps. They actually work, it's my user-experience-based reviewing software policy, and it occurs to be more reliable than the warning dialogs I receive, which are, and that's the point I wanted to stress, embarrassing for this Apple-like policy. One can blame Apple for maaaaany things, I'll be the first one to throw rocks at them, but their apps work. I don't like them, but they work.
> 
> But eOS is cool, I don't have the intention to change, it's really a cool OS to use. Just. I don't know. I would like to see them be less Apple-ish in the way they lock software installation and customization.

**Comment by vjr** [comment] 2019-12-17 18:09
I tried looking into this issue.

Ran `sysprof` and it appears that most of the time spent is in `g_utf8_collate_key` and `mpegaudioparse`. 

Modified the compare locations to always return `1` and was left with `mpegaudioparse` which seems to be related to the `GStreamer.PbUtils.Discoverer` tool taking time to scan each file being imported.

In similar issue reports some people mention the Melody app from appcenter does not exhibit this issue but when I ran it, for me, it also was slow, just that it does a better job of not blocking the main UI while import is in progress.

The other part about this crashing for large number of files I suspect the `Gee.TreeSet` being populated in `count_music_files ()` function perhaps is going over some memory limits.

Will continue to look into this to see if I am at all able to work around these suspected issues.

**Comment by maboleth** [comment] 2019-12-17 20:05
@vjr Is it possible for you to check how and what other players do? Because, for example, Lollypop does it very fast, without ever disturbing the user. Why not copy&pasting similar technique.

**Comment by grmain** [comment] 2019-12-18 20:50
> Yep and you know what? Nobody cares. :) You reported this integral issue in October and nobody from devs/mods even dared to reply you back.
> 
> Currently, Noise/Music is an abomination of an app that needs 50min to load +6500 mp3 and flac files.
> It's beyond me how devs envisioned a player app that plays your music files **when import simply does not work.** What did you expect? A hundred or so files in our libraries? In 2020? Seriously?

![image](https://user-images.githubusercontent.com/57038387/71122126-2aa3f300-21e0-11ea-9c07-a4db76a89336.png)
Wow, a little violent, isn't it?

**Comment by maboleth** [comment] 2019-12-18 20:54
^^ Well they are fast for that, aren't they? :) But when you ask for help or report a glitch, nobody cares (c).

**Comment by Dirli** [comment] 2020-02-02 10:45
A bit of intrigue
![sc102](https://user-images.githubusercontent.com/15650716/73607014-f46cd800-45c1-11ea-83d5-9f18575ec900.png)
I was also tormented by the problems described above. I tried to fix them, in my opinion it is more difficult than rewriting. This is what I am doing now.

**Comment by grmain** [comment] 2020-02-02 10:49
Seems your import went well, 11 minutes for +10000 files, that's cool! How did it occur?

**Comment by Dirli** [comment] 2020-02-02 10:54
The player is completely rewritten, slowly transferring the functionality of the stock player. I will try to publish my work in the near future.

**Comment by danrabbit** [comment] 2022-01-20 20:15
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:15 UTC
