### ISSUE TITLE
unresponsive controls

### ISSUE THREAD

**Issue by rezk2ll** [elementary/music#36] opened 2017-05-14 17:59 UTC
hello eos.
sometimes `Noise` ( Music )  stops responding to all controls ( commands ) either via the `wingpanel` widget or the Noise interface , and even the keyboard shortcuts, and the music continues but nothing gets executed.
after some delay ( minimum 6 seconds , max about 30 seconds ) all of my ( somewhat ignored ) commands will get executed sequentially . it felt like Noise was halted.
this behavior occurs every two hours tops.
i'm running eos on intel `i3-5010u` with Noise v `0.4.0.3`.
what else do i need to provide to track the issue ?
here is a picture showing a bunch of commands executed after the halt.
![sample](https://cloud.githubusercontent.com/assets/6764881/26036615/b24337e2-38d8-11e7-969b-3c81d45fa342.png)

**Comment by danrabbit** [comment] 2022-01-20 19:55
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 19:55 UTC
