### ISSUE TITLE
Removed song from playlist still plays.

### ISSUE THREAD

**Issue by jeremypw** [elementary/music#504] opened 2019-04-27 18:12 UTC
* Create a test "standard playlist"
* Add three songs to it
* Play the first song
* While playing the first song, remove the second song from the playlist.
* Press the "next" button.
* The removed song plays and no item is selected in the playlist.

**Comment by Mohelm97** [comment] 2019-04-29 02:02
I don't see this as an issue if you edit the playlist you just edit the playlist and this shouldn't affect the queue, but you edited it for the next time you add this playlist to the queue, let's see what others think :D

**Comment by jeremypw** [comment] 2019-04-29 08:22
I see your point.  I think the confusion comes because "Queue" is listed under "Playlists" in the sidebar.  Therefore a user might expect editing the queue and editing a playlist to behave the same.

**Comment by benjaminky** [comment] 2019-05-27 09:38
The first time I knew that Gibhub supported the [song ringtone](https://bestringtonemobile.com) list

**Comment by danrabbit** [comment] 2022-01-20 20:17
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:17 UTC
