### ISSUE TITLE
Change Database Keys to store ID3 and ID3v2 tags separately

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#416] opened 2018-08-30 03:10 UTC
We currently store one set of tags that doesn't bear any relationship to the embedded metadata format. There's some quite extensive documentation of the standard here: https://en.wikipedia.org/wiki/ID3

**Comment by danrabbit** [comment] 2022-01-20 20:05
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:05 UTC
