### ISSUE TITLE
App crashes at startup.

### ISSUE THREAD

**Issue by kugimiya** [elementary/music#336] opened 2018-06-15 03:20 UTC
Hello. Music app crashes at startup. :D
So, I just click at icon, app showing for 0.5 sec and got close.
So, I using Music app at standard testing Juno 5.0
App start crashing since I add music with Japanese symbols in ID3-tags at Music directory.
This is log in Terminal:
(may be developers need another log? just told me, I make it and paste.. sorry for my english, btw)
```
$ io.elementary.music 

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:44.620: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:44.629: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:44.714: Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type 'GeeBidirSortedSet' of the property on the interface 'GeeBidirSortedSet'


(io.elementary.music:11276): GLib-GObject-WARNING **: 07:14:44.847: cannot register existing type 'NoiseViewWrapper'

(io.elementary.music:11276): GLib-CRITICAL **: 07:14:44.847: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:44.847: g_type_register_dynamic: assertion 'parent_type > 0' failed
** Message: 07:14:44.852: LastFM.vala:42: Activating Last.fm plugin
** Message: 07:14:44.852: AudioPlayer.vala:37: Activating AudioPlayer Device plugin
** Message: 07:14:44.852: CDRom.vala:37: Activating CD-Rom Device plugin
** Message: 07:14:44.852: iPod.vala:37: Activating iPod Device plugin

** (io.elementary.music:11276): CRITICAL **: 07:14:44.854: noise_playback_manager_add_playback: assertion 'self != NULL' failed

** (io.elementary.music:11276): WARNING **: 07:14:44.868: LocalMedia.vala:392: Could not save media: UNIQUE constraint failed: media.uri

** (io.elementary.music:11276): CRITICAL **: 07:14:44.868: noise_media_get_rowid: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.868: DataBase.vala:111: Could not query field uri: Строка 0 не найдена (модель данных пуста)

** (io.elementary.music:11276): CRITICAL **: 07:14:44.868: noise_media_get_rowid: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.868: noise_media_get_album_hashkey: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.868: noise_media_get_album_info: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.868: noise_album_construct_from_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.868: noise_album_add_media: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.868: noise_album_get_hashkey: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.868: noise_album_get_cover_icon: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.868: noise_cover_import_construct: assertion 'album != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.902: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.904: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.904: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.905: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.905: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.905: noise_music_list_view_view_compare_func: assertion 'media_b != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.906: noise_media_get_rating: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.913: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.916: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.916: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.923: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.931: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.931: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.931: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.931: noise_media_get_album_info: assertion 'self != NULL' failed

(io.elementary.music:11276): GLib-GObject-WARNING **: 07:14:44.931: invalid (NULL) pointer instance

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:44.931: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(io.elementary.music:11276): GLib-GObject-WARNING **: 07:14:44.931: invalid (NULL) pointer instance

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:44.931: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.931: noise_albums_view_compare_func: assertion 'o_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.931: noise_albums_view_compare_func: assertion 'o_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.931: noise_albums_view_compare_func: assertion 'o_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.931: noise_media_get_rating: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.932: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.932: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.932: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.932: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.932: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.932: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.932: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.932: noise_media_get_album_info: assertion 'self != NULL' failed

** (io.elementary.music:11276): WARNING **: 07:14:44.938: LocalMedia.vala:392: Could not save media: UNIQUE constraint failed: media.uri

** (io.elementary.music:11276): CRITICAL **: 07:14:44.938: noise_media_get_rowid: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.938: DataBase.vala:111: Could not query field uri: Строка 0 не найдена (модель данных пуста)

** (io.elementary.music:11276): CRITICAL **: 07:14:44.938: noise_media_get_rowid: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.938: noise_media_get_album_hashkey: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.938: noise_media_get_album_hashkey: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.938: noise_album_add_media: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.938: noise_media_get_album_info: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.938: noise_album_construct_from_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.938: noise_album_add_media: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.938: noise_album_get_hashkey: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.938: noise_album_get_cover_icon: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.938: noise_cover_import_construct: assertion 'album != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.938: noise_media_get_rating: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.939: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.939: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.939: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.939: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.939: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.939: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.939: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.940: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.944: noise_column_browser_match_media: assertion 'm != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.945: noise_media_get_rating: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.945: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.945: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.946: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.946: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.946: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.946: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.946: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.946: noise_media_get_album_info: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.946: noise_media_get_rating: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.947: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.947: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.947: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.947: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.947: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.947: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.947: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:44.948: noise_media_get_album_info: assertion 'self != NULL' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:44.955: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:44.955: g_value_get_uint: assertion 'G_VALUE_HOLDS_UINT (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:44.955: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:44.955: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:44.956: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_uint: assertion 'G_VALUE_HOLDS_UINT (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_uint: assertion 'G_VALUE_HOLDS_UINT (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_uint: assertion 'G_VALUE_HOLDS_UINT (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_uint: assertion 'G_VALUE_HOLDS_UINT (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_uint: assertion 'G_VALUE_HOLDS_UINT (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_uint: assertion 'G_VALUE_HOLDS_UINT (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_uint: assertion 'G_VALUE_HOLDS_UINT (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_uint: assertion 'G_VALUE_HOLDS_UINT (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_uint: assertion 'G_VALUE_HOLDS_UINT (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_uint: assertion 'G_VALUE_HOLDS_UINT (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.035: g_value_get_uint: assertion 'G_VALUE_HOLDS_UINT (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.036: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.036: g_value_get_uint64: assertion 'G_VALUE_HOLDS_UINT64 (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.036: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.036: g_value_get_uint: assertion 'G_VALUE_HOLDS_UINT (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.036: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.036: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:11276): GLib-GObject-CRITICAL **: 07:14:45.036: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

** (io.elementary.music:11276): WARNING **: 07:14:45.043: LocalMedia.vala:392: Could not save media: UNIQUE constraint failed: media.uri

** (io.elementary.music:11276): CRITICAL **: 07:14:45.043: noise_media_get_rowid: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.044: DataBase.vala:111: Could not query field uri: Строка 0 не найдена (модель данных пуста)

** (io.elementary.music:11276): CRITICAL **: 07:14:45.044: noise_media_get_rowid: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.044: noise_media_get_album_hashkey: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.044: noise_media_get_album_hashkey: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.044: noise_album_add_media: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.044: noise_media_get_album_info: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.044: noise_album_construct_from_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.044: noise_album_add_media: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.044: noise_album_get_hashkey: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.044: noise_album_get_cover_icon: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.044: noise_cover_import_construct: assertion 'album != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.044: noise_media_get_rating: assertion 'self != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.045: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.045: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.045: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.045: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.045: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.045: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.045: noise_search_match_fields_to_media: assertion 'media != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.046: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.046: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.046: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.046: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.046: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.047: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.047: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.048: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.048: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.048: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.049: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.049: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.049: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.050: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.050: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.050: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.051: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.051: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.051: noise_music_list_view_view_compare_func: assertion 'media_b != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.051: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.051: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.051: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.052: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.052: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.052: noise_music_list_view_view_compare_func: assertion 'media_a != NULL' failed

** (io.elementary.music:11276): CRITICAL **: 07:14:45.052: noise_column_browser_match_media: assertion 'm != NULL' failed
**
Gtk:ERROR:../../../../gtk/gtkrbtree.c:471:_gtk_rbtree_insert_after: assertion failed: (_gtk_rbtree_is_nil (tree->root))
Аварийный останов
```

**Comment by AlexFBP** [comment] 2018-11-08 08:14
Also affecting me... 

![image](https://user-images.githubusercontent.com/6588872/48185871-5cbc0380-e304-11e8-972a-84be920ba7d9.png)

**Comment by Mohelm97** [comment] 2018-11-29 21:30
@kugimiya  Hi Mate :) 
I've tried to simulate the problem but I can't, I've tried to add Arabic and Japanese albums but they work fine, However, you can't edit from music and add a not English title or album so this is a problem.
![image](https://user-images.githubusercontent.com/1688821/49253211-f9faeb00-f41d-11e8-8088-8586a01dfe04.png)

Could you send me more stuff? like the song, if you like? :3

**Comment by kugimiya** [comment] 2018-12-12 12:35
@Mohelm97, I have good news! I think this issue can be closed, since now this error no longer occurs. 🤗
However, this error occurred exactly after I added a song with these ID3 tags:
`té - 決断は無限の扉を開くのでは無く無限の誤謬に『終止符』を打つ。`

**Comment by AlexFBP** [comment] 2018-12-17 06:36
@kugimiya which version of noise are you using? :'v

```bash
noise -h
```

**Comment by kugimiya** [comment] 2018-12-18 06:35
@AlexFBP, looks like I do not using noise. :D 
![screenshot from 2018-12-18 10-34-27](https://user-images.githubusercontent.com/8094908/50136247-a0653e00-02b0-11e9-904e-0416721ce543.png)

**Comment by kugimiya** [comment] 2018-12-18 06:40
@AlexFBP, you are using `Juno 5.0 Testing` release?

**Comment by AlexFBP** [comment] 2018-12-19 06:07
Nope @kugimiya  :( Loki. Fixed on Juno apparently?

**Comment by kugimiya** [comment] 2018-12-20 09:50
@AlexFBP, yep. Music app works correctly.

**Comment by Geoffrian** [comment] 2019-01-26 15:10
This app still crashes on startup.

**Comment by Geoffrian** [comment] 2019-01-26 15:12
This app still doesn't work correctly.  Using Juno.  Crashes on startup.  I can delete the db in ../.local/share/noise/ and then open the program, but once my music is imported the program crashes.

**Comment by carniz** [comment] 2019-03-25 18:17
Don't know what I did, it worked yesterday but now crashes on startup:

```
$ io.elementary.music 

(io.elementary.music:16333): GLib-GObject-CRITICAL **: 19:12:46.001: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:16333): GLib-GObject-CRITICAL **: 19:12:46.064: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:16333): GLib-GObject-CRITICAL **: 19:12:46.184: Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type 'GeeBidirSortedSet' of the property on the interface 'GeeBidirSortedSet'


(io.elementary.music:16333): GLib-GObject-WARNING **: 19:12:46.346: cannot register existing type 'NoiseViewWrapper'

(io.elementary.music:16333): GLib-CRITICAL **: 19:12:46.346: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:16333): GLib-GObject-CRITICAL **: 19:12:46.346: g_type_register_dynamic: assertion 'parent_type > 0' failed
** Message: 19:12:46.354: AudioPlayer.vala:37: Activating AudioPlayer Device plugin
** Message: 19:12:46.354: iPod.vala:37: Activating iPod Device plugin
** Message: 19:12:46.354: CDRom.vala:37: Activating CD-Rom Device plugin
** Message: 19:12:46.354: LastFM.vala:42: Activating Last.fm plugin

** (io.elementary.music:16333): CRITICAL **: 19:12:46.356: noise_playback_manager_add_playback: assertion 'self != NULL' failed

** (io.elementary.music:16333): CRITICAL **: 19:12:46.585: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16333): CRITICAL **: 19:12:46.585: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

(io.elementary.music:16333): GLib-GObject-WARNING **: 19:12:46.630: cannot register existing type 'NoiseGStreamerTagger'

(io.elementary.music:16333): GLib-CRITICAL **: 19:12:46.630: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:16333): GLib-GObject-CRITICAL **: 19:12:46.630: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault
```

This is on a fully updated Juno (as of today)

**Comment by asegarra** [comment] 2019-04-22 13:18
Sam here, fresh install with all updates. Opening the app and journal get's flooded non stop.

**Comment by AnwarShah** [comment] 2019-06-27 10:05
@asegarra Same here. Don't know how to disable the log. It says

    noise_playback_manager_get_current_media: assertion 'self != NULL' failed

**Comment by umbertoditommaso** [comment] 2020-05-05 07:28
Same problem here with Hera 5.1.3

g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

Segmentation Error

**Comment by danrabbit** [comment] 2022-01-20 20:04
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:04 UTC
