### ISSUE TITLE
Album view does not list tracks in the correct order

### ISSUE THREAD

**Issue by kennell** [elementary/music#616] opened 2021-01-14 16:21 UTC
## What Happened

The album view does not list tracks in the correct order, even tho the .mp3 file contains a track numeration

## Expected Behavior

Songs in a album are ordered by track number

## Steps to Reproduce

Have ~15-ish mp3s that have a ascending track numbers in their metadata, import them into the application, check the album view and see that they are ordered at random.

I've checked the mp3 metadata e.g. with `exiftool` 

## Platform Information

elementary OS 5.1.7 Hera

**Comment by ghsttwn** [comment] 2021-08-20 17:00
This is still happening in elementary OS 6 Odin. Can't believe this hasn't been fixed. 😞

**Comment by danrabbit** [comment] 2022-01-20 20:20
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:20 UTC
