### ISSUE TITLE
Replace settings panel with a more sensible set of settings in a popover

### ISSUE THREAD

**Issue by hanaral** [elementary/music#615] opened 2020-12-24 00:29 UTC
## Problem
I shouldn't have to explain why dedicated settings windows suck - they are not only just anti-user by pushing them outside of the main window of media app, but most of all, it even says in the elementary HIG that design choices shouldn't be up to the users: _"[When considering adding options to your app, try to strike a balance of making your app more accessible without pushing design work onto your users.](https://elementary.io/docs/human-interface-guidelines#accessible-configuration)"_

## Proposal
Purge the settings of things that arguably shouldn't be in there, such as;
- Moving the "continue playing when closed" setting to a global toggle in System Settings that applies to all music apps (a new gsetting that developers such as Alain can hook off)
- Moving the "Music folder location" in to a file open dialogue that is hidden in popover unless the toggles off the "Use default music folder" switch

## Prior Art
![Screenshot from 2020-12-24 00-09-47](https://user-images.githubusercontent.com/58219504/103045450-72d8bc80-457c-11eb-8195-52fe716e52e7.png)
Ephemeral is a pretty good example of how settings UX _should_ be done

@cassidyjames could you provide some input if you see it as relevant (pretty sure this is your realm of things)

**Comment by danrabbit** [comment] 2022-01-20 20:20
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:20 UTC
