### ISSUE TITLE
Pre-scan fails because of too many levels of symbolic links

### ISSUE THREAD

**Issue by okin** [elementary/music#507] opened 2019-06-24 19:09 UTC
I can not start this app on elementaryOS 5.0, running version _5.0.4+r2721+pkg114~ubuntu5.0.1_.
It seems to stumble upon symbolic links and never finishes the attempt to start up.

```
19:33:24 niko@elementary ~ io.elementary.music                                             

** (io.elementary.music:1998): WARNING **: 19:57:49.683: FileOperator.vala:99: Could not pre-scan music folder. Progress percentage may be off: Fehler beim Holen der Informationen für Datei »/home/niko/.steam/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/steam/root/steam/steam/root/ubuntu12_32/steam-runtime/i386/usr/share/locale/hi/LC_MESSAGES/gtk20-properties.mo«: Zu viele Ebenen aus symbolischen Links


** (io.elementary.music:1998): WARNING **: 19:57:49.804: FileOperator.vala:99: Could not pre-scan music folder. Progress percentage may be off: Fehler beim Holen der Informationen für Datei »/home/niko/.steam/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/steam/root/steam/steam/root/ubuntu12_32/steam-runtime/amd64/installed/libtasn1-6_4.7-3ubuntu0.16.04.3~steamrt1.1+srt1_amd64.md5«: Zu viele Ebenen aus symbolischen Links


** (io.elementary.music:1998): WARNING **: 20:30:11.809: FileOperator.vala:99: Could not pre-scan music folder. Progress percentage may be off: Fehler beim Holen der Informationen für Datei »/home/niko/.steam/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/steam/root/root/steam/root/root/steam/bin32/steam-runtime.old/i386/installed/libxrender1_0.9.6-2ubuntu0.2+srt2_i386«: Zu viele Ebenen aus symbolischen Links


** (io.elementary.music:1998): WARNING **: 20:50:43.014: FileOperator.vala:99: Could not pre-scan music folder. Progress percentage may be off: Fehler beim Holen der Informationen für Datei »/home/niko/.steam/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/root/steam/steam/root/steam/root/steam/root/steam/steam/appcache/httpcache/58/58838850dfc1b3d98d7015330552afc09fa30386_da39a3ee5e6b4b0d3255bfef95601890afd80709«: Zu viele Ebenen aus symbolischen Links
```
This message will repeat without end and no app will start.

```
$ ls -l ~/.steam/root
lrwxrwxrwx 1 niko niko 17 Jun 15 19:08 /home/niko/.steam/root -> /home/niko/.steam
```

I think that the app tries to traverse the directories in `.steam` without realising it is visiting a place where it has been before.
Memorizing where it has been could be a possible fix for this. Killing of the functionality to follow links might break things for some people.

Another improvement from this could be that hidden folders inside the users home aren't searched.

**Comment by okin** [comment] 2019-06-25 18:52
I did remove the link today and after about 70 minutes I got the following:

```
$ io.elementary.music

(io.elementary.music:2684): GLib-GObject-CRITICAL **: 20:22:35.533: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:2684): GLib-GObject-CRITICAL **: 20:22:35.567: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:2684): GLib-GObject-CRITICAL **: 20:22:35.889: Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type 'GeeBidirSortedSet' of the property on the interface 'GeeBidirSortedSet'


(io.elementary.music:2684): GLib-GObject-WARNING **: 20:32:16.625: cannot register existing type 'NoiseViewWrapper'

(io.elementary.music:2684): GLib-CRITICAL **: 20:32:16.625: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:2684): GLib-GObject-CRITICAL **: 20:32:16.625: g_type_register_dynamic: assertion 'parent_type > 0' failed
** Message: 20:32:16.628: LastFM.vala:42: Activating Last.fm plugin
** Message: 20:32:16.628: iPod.vala:37: Activating iPod Device plugin
** Message: 20:32:16.628: CDRom.vala:37: Activating CD-Rom Device plugin
** Message: 20:32:16.628: AudioPlayer.vala:37: Activating AudioPlayer Device plugin

** (io.elementary.music:2684): CRITICAL **: 20:32:16.632: noise_playback_manager_add_playback: assertion 'self != NULL' failed

** (io.elementary.music:2684): CRITICAL **: 20:32:16.974: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:2684): CRITICAL **: 20:32:16.974: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:2684): CRITICAL **: 20:32:17.219: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:2684): CRITICAL **: 20:32:17.219: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
```

The last message is since then about every 300 miliseconds. This seems to be already reported as #505.

No window is showing up.

**Comment by danrabbit** [comment] 2022-01-20 20:16
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:16 UTC
