### ISSUE TITLE
window hangs while drawing suggested tracks

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#53] opened 2017-08-08 15:19 UTC
steps to reproduce:
1 set up your lastfm account
2 play a track
3 scroll up and down
4 notice the scrolling stop just before the suggested tracks list appears

really everything goes, but this is the quickest simplest test.

**Comment by Nine-H** [comment] 2017-08-20 00:08
it's not just drawing: it hangs when they load when the sidebar is hidden too.

**Comment by danrabbit** [comment] 2017-12-02 00:42
It sounds like from discussion in Slack that we're okay with just dropping this feature

**Comment by Nine-H** [comment] 2017-12-07 01:02
it happened in the info sidebar. I'm not sure what happens if you link a last.fm account in master, because I never figured out the line that caused the block.

**Comment by danrabbit** [comment] 2022-01-20 19:57
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 19:57 UTC
Labels: Priority: Medium, Status: Confirmed
