### ISSUE TITLE
Don't suggest to move unrecognized files to Trash on each run

### ISSUE THREAD

**Issue by bjorn** [elementary/music#470] opened 2018-12-19 15:33 UTC
Part of my music is stored in a format that this application does not recognize (`.it` - Impulse Tracker files). Every time I open Music, it suggests to move these "corrupted files" to Trash:

![io elementary music_276](https://user-images.githubusercontent.com/531764/50229750-4bf2b900-03ab-11e9-9d58-97fd1034bca5.png)

I would suggest to only see files as "corrupted" when they have a recognized file extension, but still fail to load, since when all unrecognized files are marked as such this helpful message is actually quite dangerous.

In addition, it would be nice if the feature could be turned off entirely. I generally would expect my music player to just ignore files it doesn't recognize.

**Comment by Mohelm97** [comment] 2018-12-19 18:03
Hi @bjorn 

Me too, I think messing with the files and deleting stuff is not the music player job :(

Anyway Hooray, you can play `.it` files but just installing the `gstreamer1.0-plugins-bad`
So you got both the message won't appear and you can play the files :D :tada:

**Comment by ryanfelder** [comment] 2020-09-23 18:42
This is the big thing preventing me from using Music as my primary app. 
All I want is an 'Ignore forever' button next to the Ignore button on this warning.

If new files pop in that it can't read, I'm cool with a new warning, but I don't want to have to ignore the same files every time I open the app, please.

**Comment by ryanfelder** [comment] 2020-09-23 18:42
For what it's worth, mine is choking on 6000 audacity project files.

**Comment by jeremypw** [comment] 2020-09-24 16:04
@ryanfelder  What file type (mime type) is it choking on?  Music should only consider valid audio mime-types when attempting to import and the import should generally  only fail if a plugin is missing or the file is corrupted.

**Comment by ryanfelder** [comment] 2020-09-24 16:07
au file type, elementary files calls them out as audio/basic

**Comment by jeremypw** [comment] 2020-09-24 16:09
OK, thanks. That is one of the file types that is regarded "acceptable" in the Music code.  I need to check whether there is a gstreamer plugin for that type.

**Comment by ryanfelder** [comment] 2020-09-24 16:15
I appreciate that. 

I'd still like to request an option to ignore 'corrupt' files on future runs. I do not like my music player enforcing it's design decisions on me and the absence of this feature really is doing nothing but nagging me about my library. It's not nice.

Perhaps I have a file that isn't strictly compliant, but plays in another application, for example. I'd rather not be repeatedly bugged by Music because Music can't play it.

**Comment by jeremypw** [comment] 2020-09-24 16:25
Understood. I certainly agree that it is not Music's job to trash files etc.  I was considering having an option to open the relevant folder in the filemanager instead.

**Comment by jeremypw** [comment] 2020-09-24 16:27
So, I just downloaded a sample `.au` audio file from Wikipedia and Music imported that without problem for me.

**Comment by ryanfelder** [comment] 2020-09-24 16:33
The files for me are the files created by Audacity when I create an Audacity project. 
Audacity has no trouble with its own files, obviously, but I generally also have no other example use cases for au files.

Now that I really think about it, I'd rather Music not try to play them... If it did, I'd get things like, a four minute track of a hi-hat being shuffled in with my other music. Perhaps an option in Music to uncheck/ignore entire folders in my library would be useful.

By default it could select all folders recursively, but if a user wants to exclude, lets say, their entire catalog of X or Y from Music, they can do that without jumping through playlist hoops or having to reorganize their music on the filesystem lebel into 'Allowed to be shuffled' and 'Not allowed to be shuffled'

**Comment by jeremypw** [comment] 2020-09-24 16:44
A number of possible improvements come to mind, e.g. allowing the user to exclude certain filetypes, but it easier to get simple incremental fixes merged.

**Comment by jeremypw** [comment] 2020-09-24 16:46
Do you need to keep your Audacity projects in a subfolder of your Music library? Can you create a separate folder in your home folder or elsewhere to those?

**Comment by ryanfelder** [comment] 2020-09-24 17:00
I'd rather configure my player than reorganize my music.

**Comment by bjorn** [comment] 2020-09-24 20:04
I see that in both my case and @ryanfelder's case, the file types are generally "audio files", but they fail to play because some gstreamer plugin has not been installed. I consider it a rather serious bug to tell the user the files are corrupt in this case. Simply ignoring them would be an improvement. Ideally, the user would be directed to install the necessary plugins (though it should still be something that can be declined once).

**Comment by danrabbit** [comment] 2022-01-20 20:10
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:10 UTC
