### ISSUE TITLE
Not opening when having Proton from steam

### ISSUE THREAD

**Issue by TheArchKnight** [elementary/music#498] opened 2019-04-07 00:58 UTC
Hi, the Music app cannot open, because is doing an pre-scan for looking for the music folder. It will only open with sudo, as proton from Steam, it cannot be acces by an app without sudo.

Any idea?

` (io.elementary.music:12752): WARNING **: 19:52:31.074: FileOperator.vala:99: Could not pre-scan music folder. Progress percentage may be off: Error opening directory '/home/anorak/.local/share/Steam/steamapps/common/Proton 3.16/dist/share/default_pfx/dosdevices/z:/dev/fd/16/.local/share/Steam/steamapps/common/Proton 3.16/dist/share/default_pfx/dosdevices/z:/lost+found'`

That is the log if i try to open it via terminal.

**Comment by danrabbit** [comment] 2022-01-20 20:17
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:17 UTC
