### ISSUE TITLE
When I start eOS music app, it starts flickering

### ISSUE THREAD

**Issue by Mazafesio** [elementary/music#228] opened 2017-12-23 12:10 UTC
https://imgur.com/a/zbruj

I "reposted" this question from StackExchange but a bit inactive so I'm posting the question here if somebody can help me.

When I start the eOS Music app, it starts flickering as the video shows then it stops flickering and updating the music library, then the albums view doesn't work and list view works badly. The three column view works well.

Also, I can't import music because the option is not highlighted.

**Comment by danrabbit** [comment] 2022-01-20 20:02
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:02 UTC
