### ISSUE TITLE
All musics are added to the playlist when you try to added one or a certain set of musics

### ISSUE THREAD

**Issue by ghost** [elementary/music#442] opened 2018-10-19 13:54 UTC
Hi! Thanks for the awesome work with Elementary OS!
When I try to add a song to a certain playlist, all songs are added to the playlist instead.
I'm adding to the playlist by right-clicking the desired music and "add to the playlist" and choosing the desired one.

**Comment by aadilayub** [comment] 2018-10-20 04:37
This is a duplicate of https://github.com/elementary/music/issues/428

**Comment by BaptisteGelez** [comment] 2018-10-20 07:19
@aadilayub not sure, this issue seems to be about playlist, while #438 is concerning the queue.

**Comment by aadilayub** [comment] 2018-10-20 08:53
Oh, my bad! I misread the description.

**Comment by dolphinoracle** [comment] 2018-10-26 19:31
from some observations I've been watching pretty close and while the display of the playlist and/or queue in question does list all songs in the library, music appears to only be playing those on that have been added to the list in question.    but the display of the list is completely incorrect and therefore makes the system almost unusable.

**Comment by danrabbit** [comment] 2022-01-20 20:10
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:10 UTC
