### ISSUE TITLE
Multiple songs info editing

### ISSUE THREAD

**Issue by anddam** [elementary/music#49] opened 2017-07-13 14:07 UTC
Add info editing for a selection of multiple songs.

**Comment by pablojimpas** [comment] 2021-04-09 21:20
This is already possible using the arrows in the lower left corner, perhaps the layout could be improved and/or gestures could be implemented using libhandy, otherwise this issue should be closed.

![Captura de pantalla de 2021-04-09 23 11 46](https://user-images.githubusercontent.com/51208565/114241343-48730980-9989-11eb-9e1c-4132956514e2.png)

**Comment by danrabbit** [comment] 2022-01-20 19:56
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 19:56 UTC
Labels: Priority: Wishlist, Status: Confirmed
