### ISSUE TITLE
Error:  error while loading shared libraries: libio.elementary.music-core.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by iman-salmani** [elementary/music#601] opened 2020-09-17 11:32 UTC
### Command: io.elementary.music
output:
```
io.elementary.music: error while loading shared libraries: libio.elementary.music-core.so.0: cannot open shared object file: No such file or directory
```
### Installation type:
build Source code version 5.0.5
### My system:
![Screenshot from 2020-09-17 15-55-16](https://user-images.githubusercontent.com/32843050/93464321-3bfc6600-f8fe-11ea-9df6-ae910cf8927e.png)
### Time of error
It was good after construction and installation.
I used it several times.
Then I got this error.

> i used libhandy-0.0-dev

**Comment by jeremypw** [comment] 2020-09-22 08:41
DId you uninstall Music from the AppCenter (or terminal) before building from source? Maybe there was a conflicting update.

**Comment by jeremypw** [comment] 2020-09-22 08:42
You may need to build and install again.  If you clone the git repository you can pull the latest changes before building.

**Comment by rakshit087** [comment] 2021-11-01 14:37
I have having same issue, I removed the preinstalled Music Application before building to avoid conflicts.

**Comment by danrabbit** [comment] 2022-01-20 20:21
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:21 UTC

**Comment by rakshit087** [comment] 2022-01-20 20:41
Great thanks :+1:
