### ISSUE TITLE
Music won't import or play my .wma files

### ISSUE THREAD

**Issue by 2whlrider** [elementary/music#700] opened 2022-03-12 18:26 UTC
"Unable to import 1012 items. The files may be damaged." Then I have the option to ignore the warning or trash all my .wma files. This is the Music version that is shipping with Elementary 6.1 Jolnir. Sorry, I don't know where to find the version number of Music. Older versions of Music have no trouble loading or playing other files besides mp3.

**Comment by 2whlrider** [comment] 2022-03-14 02:06
Music version 5.1.1 I think.

**Comment by 2whlrider** [comment] 2022-04-06 03:18
This problem happened to Music (called Noise at the time, I think) after a gstreamer update was pushed out. Something to do with filters in gstreamer.

**Comment by danrabbit** [comment] 2022-04-06 20:44
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-04-06 20:44 UTC
