### ISSUE TITLE
Remove from library action does not always remove from view list

### ISSUE THREAD

**Issue by jeremypw** [elementary/music#332] opened 2018-05-07 18:17 UTC
* Select first or last item in library list view
* Press delete or choose "remove from library" context option.
* The row does not disappear (deleting it again does nothing)
* Select the next row - this can be deleted and it disappears.

**Comment by danrabbit** [comment] 2022-01-20 20:04
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:04 UTC
