### ISSUE TITLE
Make EQ accessible through gear menu

### ISSUE THREAD

**Issue by elegaanz** [elementary/music#116] opened 2017-12-02 11:54 UTC
And put it in a popup window.

**Comment by danrabbit** [comment] 2017-12-02 17:52
I'm -1 here. I don't think making the EQ less discoverable is a good move

**Comment by Bat41** [comment] 2017-12-02 21:15
Where should we put it then? Add another button for it in the header bar?

**Comment by mrnhmath** [comment] 2017-12-04 16:46
Is EQ a popular feature? I personally never found a use to it.

**Comment by Nine-H** [comment] 2017-12-05 00:34
@mrnmath EQ lets you tune your headphones and play music over a PA without making the windows rattle. It's pretty important.

**Comment by danrabbit** [comment] 2022-01-20 20:00
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:00 UTC
Labels: Priority: Wishlist
