### ISSUE TITLE
Bitrate Field does not populate

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#414] opened 2018-08-24 01:55 UTC
When column browsing the bitrate field is usually blank

expected behaviour: get the bitrate while importing, check database bitrate against actual gstreamer bitrate while playing, identify VBR tracks.

**Comment by danrabbit** [comment] 2022-01-20 20:05
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:05 UTC
