### ISSUE TITLE
It's not possible to rescan covers

### ISSUE THREAD

**Issue by artemanufrij** [elementary/music#50] opened 2017-07-26 19:29 UTC
If import throws an error, covers stays blank. It's not possible to rescan covers of imported files.

**Comment by danrabbit** [comment] 2022-01-20 19:57
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 19:57 UTC
Labels: Priority: Wishlist, Status: Confirmed, Needs design
