### ISSUE TITLE
iPod Sync Broken

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#101] opened 2017-11-28 07:59 UTC
I tested 0.4.1, GIt master, and 0.42 and multiple devices. You can preview music, delete  music, and rename the ipod, but sync will always fail with "the device is already doing an operation".

![screenshot from 2017-11-28 18 53 42](https://user-images.githubusercontent.com/20123543/33308343-3018e7a8-d46e-11e7-9afd-94bf5b1a9a17.png)

**Comment by danrabbit** [comment] 2017-12-02 00:38
It seems like libgpod hasn't been updated in several years. It might just be better to remove iDevice support since it probably can't be fixed for current gen devices

**Comment by nikkilr88** [comment] 2019-05-16 18:10
I'm having this same problem. Are there any plans to fix this?

**Comment by dchirva** [comment] 2019-09-07 10:22
Same problem. 
Ipod Classic 160 Gb.
Need to be fixed.

**Comment by Nine-H** [comment] 2019-09-09 00:58
https://support.apple.com/en-us/HT201624

**Comment by danrabbit** [comment] 2022-01-20 20:23
Duplicate of #635

**Closed by danrabbit** 2022-01-20 20:23 UTC
Labels: Priority: Medium, Status: Confirmed
