### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by phocean** [elementary/music#280] opened 2018-02-14 16:00 UTC
I don't know how it happened exactly, but Noise caused a huge memory leak on my system:

![capture d ecran de 2018-02-14 15-22-49](https://user-images.githubusercontent.com/4280885/36213897-3930b2a4-11a8-11e8-88fe-c4046507f8e7.png)

I could not get much trace other than that (I had to reboot and lost logs from the previous boot).

**Comment by danrabbit** [comment] 2022-01-20 20:07
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:07 UTC
