### ISSUE TITLE
Missing music in library and icon in plank.

### ISSUE THREAD

**Issue by ghost** [elementary/music#399] opened 2018-07-26 22:14 UTC
After closing and reopening the music app, the libray in folder or cover view dissapears, it shows the music in "showing in columns" but with no action (play,stop,etcc), also after the last updates music stayed without icon in plank or even the apps menu.
![captura de ecra de 2018-07-26 23 10 30](https://user-images.githubusercontent.com/23345027/43291487-826e41ec-9129-11e8-9b3e-d9eea1e957fd.png)
![captura de ecra de 2018-07-26 23 10 58](https://user-images.githubusercontent.com/23345027/43291488-828e1576-9129-11e8-98b3-7b6a427d0372.png)
![captura de ecra de 2018-07-26 23 11 21](https://user-images.githubusercontent.com/23345027/43291491-85db9a64-9129-11e8-91be-53d5b72a36d6.png)

**Comment by darthmaulbr** [comment] 2018-07-30 04:22
Confirmed here, i have the same issues.

**Comment by danrabbit** [comment] 2022-01-20 20:05
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:05 UTC
