### ISSUE TITLE
The "number of songs on the queue" 's label are displaying the wrong number after empty the queue

### ISSUE THREAD

**Issue by ghost** [elementary/music#443] opened 2018-10-19 14:17 UTC
The label keep showing the number of songs that was in the queue before be emptied
![captura de tela de 2018-10-19 11 09 14](https://user-images.githubusercontent.com/33835731/47223583-00626580-d390-11e8-9001-e3767bc5e255.png)

**Comment by danrabbit** [comment] 2022-01-20 20:10
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:10 UTC
