### ISSUE TITLE
Plugins are depending on the app

### ISSUE THREAD

**Issue by elegaanz** [elementary/music#260] opened 2018-01-14 09:33 UTC
Plugins should only depend on the core library, but they need the app files to build.

**Comment by danrabbit** [comment] 2022-01-20 20:03
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:03 UTC
Labels: Priority: Medium
