### ISSUE TITLE
"Keep music folder organized" unclear

### ISSUE THREAD

**Issue by ghost** [elementary/music#468] opened 2018-12-09 07:46 UTC
Music should prompt on first run whether the user wants this option and what it means. The meaning is unclear: organize how? by doing what? If the user is unclear of the result, this option has no benefit and has potential drawbacks. Even a tooltip in the options menu explaining the actual behavior of this option would help.

In other words, the first run of a desktop program should not change any user data without the user's explicit permission!

**Comment by danrabbit** [comment] 2022-01-20 20:10
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:10 UTC
