### ISSUE TITLE
Cannot edit songs info

### ISSUE THREAD

**Issue by heinhtoohtookyaw** [elementary/music#580] opened 2020-04-05 15:09 UTC
I tried to add songs info like artist's name, album's name, album's art, etc. But it's didn't work. And current informations were not also showed when input dialog was opened.

**Comment by jeremypw** [comment] 2020-04-12 15:45
Duplicate of #451

**Comment by jeremypw** [comment] 2020-04-12 16:27
This has started working for me after building and installing the app from source.  Its unclear why.  This app uses libgda to store the metadata.

**Comment by torikulhabib** [comment] 2020-05-30 01:03
this problem can use my inytag support set picture mp3 mp4 flac.
https://github.com/torikulhabib/InyTag

**Comment by danrabbit** [comment] 2022-01-20 20:17
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:17 UTC
Labels: Status: Duplicate
