### ISSUE TITLE
Shuffle and previous button

### ISSUE THREAD

**Issue by aurabindo** [elementary/music#440] opened 2018-10-18 05:24 UTC
I'd prefer if while I'm on shuffle mode, hitting the "Previous" button would take me to the last played song rather than another shuffled track! Only "Next: should actually play a shuffled song.

**Comment by danrabbit** [comment] 2022-01-20 20:12
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:12 UTC
