### ISSUE TITLE
The audio keeps playing after close the music app

### ISSUE THREAD

**Issue by andirsun** [elementary/music#613] opened 2020-10-26 15:08 UTC
## What Happened
When I open every audio file, and I want to close the app to open other, the track keeps running in background.
If I open other track, both keep listening.

## Expected Behavior

The expected behavior is stop the music after close the app.

## Steps to Reproduce

I dont know if it works, but I opened the app in the terminal to see the log and I found this. 
1. Open the terminal
2. open io.elementary.music
3. check the log

### Logs

```
** (io.elementary.music:22009): CRITICAL **: 09:46:51.611: noise_playback_manager_add_playback: assertion 'self != NULL' failed

** (io.elementary.music:22009): CRITICAL **: 09:46:51.811: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

```
## Platform Information

![Screenshot from 2020-10-26 10-05-08](https://user-images.githubusercontent.com/22928302/97189605-c7291100-1772-11eb-8527-a4c137c3eddf.png)

## How I temporal solve it 
After close the app an the music keeps running, I go to gnome-system-monitor and I manually kill the io.elementary.music process to close the app.

**Comment by cassidyjames** [comment] 2020-10-26 20:38
First, this is by design. You can always pause the music using the in-app controls, the sound menu in the panel, or keyboard media keys to stop the music. If the music is paused, the app closes as expected. When playing, the music will continue playing when the window is closed unless explicitly stopped. This is similar by design to how mobile OSes work, and follows our Human Interface Guidelines around [Closing an app](https://elementary.io/docs/human-interface-guidelines#closing). With apps designed for elementary OS, closing behaves more like “backgrounding” an app or "going home" in a mobile OS; if it makes sense, the app keeps running in the background to provide services to the user or system.

That said, I understand it may be an adjustment when you're not expecting it. My recommendation would be to pause the music when you're done playing, either from the app itself of the sound menu if the window is closed.

**Comment by cassidyjames** [comment] 2020-10-26 20:39
To follow up, the actual issue here may be that there are two music files playing at the same time; that definitely should not happen. I wonder if #543 would actually resolve this use case better.

**Comment by andirsun** [comment] 2020-10-26 20:42
> First, this is by design. You can always pause the music using the in-app controls, the sound menu in the panel, or keyboard media keys to stop the music. If the music is paused, the app closes as expected. When playing, the music will continue playing when the window is closed unless explicitly stopped. This is similar by design to how mobile OSes work, and follows our Human Interface Guidelines around [Closing an app](https://elementary.io/docs/human-interface-guidelines#closing). With apps designed for elementary OS, closing behaves more like “backgrounding” an app or "going home" in a mobile OS; if it makes sense, the app keeps running in the background to provide services to the user or system.
> 
> That said, I understand it may be an adjustment when you're not expecting it. My recommendation would be to pause the music when you're done playing, either from the app itself of the sound menu if the window is closed.

Ohh I understand, but why when I close the app the icon dissapears from the dock ? 
I mean, if the elementary guidelines are send to the background apps why the icon not stay open in the dock.

**Comment by danrabbit** [comment] 2020-10-26 22:32
@andirsun the dock should not be considered a task manager and does not accurately reflect whether apps are running or not

**Comment by andirsun** [comment] 2020-10-27 01:00
> @andirsun the dock should not be considered a task manager and does not accurately reflect whether apps are running or not

@danrabbit So, its normal to close the app (icon dissapear from dock and music keeps playing), and then open other song and then both songs are playing ?

**Comment by danrabbit** [comment] 2020-10-27 01:04
@andirsun obviously not and I didn't say that. What I said was that whether the icon is in the dock or not does not indicate if the app is running or not

**Comment by andirsun** [comment] 2020-10-27 01:07
> @andirsun obviously not and I didn't say that. What I said was that whether the icon is in the dock or not does not indicate if the app is running or not

Sure!, then do you think I need to modify the issue report ?

**Comment by dagolinuxoid** [comment] 2021-04-29 19:17
Settings -> desktop integration -> turn off continue playback when closed option

**Closed** 2021-05-03 23:14 UTC
Labels: Status: Design Conflict
