### ISSUE TITLE
error adding symbols

### ISSUE THREAD

**Issue by Marukesu** [elementary/music#276] opened 2018-02-10 13:13 UTC
music fail building with this error
```
/usr/lib/gcc/x86_64-unknown-linux/6.2.0/../../../../x86_64-unknown-linux/bin/ld: /usr/lib/gcc/x86_64-unknown-linux/6.2.0/../../../../lib/libgio-2.0.so: undefined reference to symbol 'inflateEnd'
//lib/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Error: module music: Child process exited with code ```

**Comment by danrabbit** [comment] 2022-01-20 20:07
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:07 UTC
