### ISSUE TITLE
Allow sorting by artist then release year in Library view.

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/music#475] opened 2019-01-16 12:26 UTC
Sort by:
1. Artist Name (A-Z)
2. Album Year (Early to Late)
  a. Disc Number (0-...)
3. Track Number (0-...)

**Comment by lewisgoddard** [comment] 2019-01-16 12:35
Never mind, this appears to be already implemented. 
![image](https://user-images.githubusercontent.com/831389/51249441-2eeddd80-198b-11e9-85a0-90de0868cf89.png)

**Comment by arshubham** [comment] 2019-01-16 12:38
@lewisgoddard you used the screenshot from Melody. Sort is not implemented in default music app in library view.

**Comment by danrabbit** [comment] 2022-01-20 20:09
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:09 UTC
