### ISSUE TITLE
Music crashes on import

### ISSUE THREAD

**Issue by Shnatsel** [elementary/music#439] opened 2018-10-17 19:29 UTC
Attempting to import my music library to Music crashes the app. I'm using the version shipping in the Juno release image.

I would appreciate pointers on obtaining a useful backtrace since posting 16Gb of music to reproduce a bug is probably not worth it.

**Comment by BaptisteGelez** [comment] 2018-10-17 19:33
Normally, you can run `gdb io.elementary.music`, then launch it with `run`, make it crash by importing your music, and when it crashes, use `bt` in GDB to get the backtrace.

**Comment by Shnatsel** [comment] 2018-10-17 20:38
I've done it, the backtrace is attached, but it looks completely useless to me because of missing debug symbols. Noise no longer builds a -dbg package, so any function names inside it just show up as ??? in the backtrace. I guess I'll have to bug OS devs about proper debug packages.

[noise-backtrace-useless.txt](https://github.com/elementary/music/files/2489166/noise-backtrace-useless.txt)

**Comment by Shnatsel** [comment] 2018-10-17 21:15
I have obtained a somewhat useful backtrace using sorcery. The relevant excerpt is:

```
[New Thread 0x7fff7effd700 (LWP 14460)]
**
ERROR:hashset.c:1558:gee_hash_set_iterator_real_next: assertion failed: (_stamp == _set._stamp)

Thread 882 "io.elementary.m" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff9a7fc700 (LWP 14447)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: Нет такого файла или каталога.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff431a801 in __GI_abort () at abort.c:79
#2  0x00007ffff73d5025 in g_assertion_message (domain=domain@entry=0x0, file=file@entry=0x7ffff79593a1 "hashset.c", line=line@entry=1558, 
    func=func@entry=0x7ffff79593e0 <__func__.13614> "gee_hash_set_iterator_real_next", 
    message=message@entry=0x7fffcc060f80 "assertion failed: (_stamp == _set._stamp)") at ../../../../glib/gtestutils.c:2532
#3  0x00007ffff73d508a in g_assertion_message_expr (domain=domain@entry=0x0, file=file@entry=0x7ffff79593a1 "hashset.c", line=line@entry=1558, 
    func=func@entry=0x7ffff79593e0 <__func__.13614> "gee_hash_set_iterator_real_next", expr=expr@entry=0x7ffff795938b "_stamp == _set._stamp")
    at ../../../../glib/gtestutils.c:2555
#4  0x00007ffff790e072 in gee_hash_set_iterator_real_next (base=<optimized out>) at hashset.c:1558
#5  0x000055555559be00 in __lambda32_ (_data17_=<optimized out>, _data17_=<optimized out>) at io.elementary.music@exe/src/GStreamer/CoverImport.c:174
#6  ___lambda32__gthread_func (self=<optimized out>) at io.elementary.music@exe/src/GStreamer/CoverImport.c:264
#7  0x00007ffff73d5e85 in g_thread_proxy (data=0x5555567da280) at ../../../../glib/gthread.c:784
#8  0x00007ffff38256db in start_thread (arg=0x7fff9a7fc700) at pthread_create.c:463
#9  0x00007ffff43fb88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

Full gdb log: [noise-backtrace-somewhat-useful.txt](https://github.com/elementary/music/files/2489311/noise-backtrace-somewhat-useful.txt)

Looks like `CoverImport.c` is involved. Is there perhaps a log level setting that would make Noise print which file it's currently trying to import? That would help narrow it down to a specific file that's causing the crash.

**Comment by pemex44** [comment] 2020-06-30 14:42
I have the same issue. Will try to get debugging info to track the issue

**Comment by danrabbit** [comment] 2022-01-20 20:12
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:12 UTC
