### ISSUE TITLE
"Move corrupted files to trash" does not move the files to trash

### ISSUE THREAD

**Issue by ylytkin** [elementary/music#552] opened 2019-10-19 05:49 UTC
I have some temporary files in my music directories like these:

![image](https://user-images.githubusercontent.com/43873680/67138500-5dfbed00-f244-11e9-8b7d-85186a389c31.png)

These are added automatically by my cloud service. The music player does not recognize these and proposes to move these to trash. I don't mind, I would like that. But when I check the "Move to trash" box and press "Move to trash":

![image](https://user-images.githubusercontent.com/43873680/67138512-9e5b6b00-f244-11e9-859c-bea16a63272c.png)

Afterwards the files are still there, and this box shows up again every time I load the music player until I go and delete these files by hand.

It is possible that this is caused by the fact that these files are on an NTFS partition (I used to have problems with even loading the music files from an NTFS partition, but it got fixed at some point).

**Comment by danrabbit** [comment] 2022-01-20 20:15
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:15 UTC
