### ISSUE TITLE
Edit Metadata Inline in list view

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#82] opened 2017-10-31 05:36 UTC
seems silly to have a dialog to edit metadata when what's wrong is clearly already staring you in the face. I think it would be cool to have a mode or plugin to edit your library metadata in the list view with a spreadsheet alike interface.

Edit: this is one of my more _out there_ ideas, so please don't close it till I've thought about the specifics.

**Comment by danrabbit** [comment] 2022-01-20 20:01
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:01 UTC
