### ISSUE TITLE
close app

### ISSUE THREAD

**Issue by iman-salmani** [elementary/music#600] opened 2020-09-15 18:22 UTC
i play music and close window
after again opening app:(terminal output)
```
(io.elementary.music:13801): GLib-GObject-CRITICAL **: 22:35:55.708: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:13801): GLib-GObject-CRITICAL **: 22:35:55.797: Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type 'GeeBidirSortedSet' of the property on the interface 'GeeBidirSortedSet'


(io.elementary.music:13801): GLib-GObject-WARNING **: 22:35:56.002: cannot register existing type 'NoiseViewWrapper'

(io.elementary.music:13801): GLib-CRITICAL **: 22:35:56.002: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:13801): GLib-GObject-CRITICAL **: 22:35:56.002: g_type_register_dynamic: assertion 'parent_type > 0' failed
** Message: 22:35:56.019: AudioPlayer.vala:37: Activating AudioPlayer Device plugin
** Message: 22:35:56.019: CDRom.vala:37: Activating CD-Rom Device plugin
** Message: 22:35:56.019: iPod.vala:37: Activating iPod Device plugin
** Message: 22:35:56.019: LastFM.vala:42: Activating Last.fm plugin

** (io.elementary.music:13801): CRITICAL **: 22:35:56.021: noise_playback_manager_add_playback: assertion 'self != NULL' failed

(io.elementary.music:13801): GLib-GObject-WARNING **: 22:35:56.021: invalid (NULL) pointer instance

(io.elementary.music:13801): GLib-GObject-CRITICAL **: 22:35:56.021: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(io.elementary.music:13801): GLib-GObject-WARNING **: 22:35:56.021: invalid (NULL) pointer instance

(io.elementary.music:13801): GLib-GObject-CRITICAL **: 22:35:56.021: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(io.elementary.music:13801): GLib-GObject-WARNING **: 22:35:56.021: invalid (NULL) pointer instance

(io.elementary.music:13801): GLib-GObject-CRITICAL **: 22:35:56.021: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (io.elementary.music:13801): CRITICAL **: 22:35:56.248: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:13801): CRITICAL **: 22:35:56.248: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:13801): CRITICAL **: 22:35:56.462: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:13801): CRITICAL **: 22:35:56.462: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

(io.elementary.music:13801): GLib-GObject-WARNING **: 22:35:56.476: cannot register existing type 'NoiseGStreamerTagger'

(io.elementary.music:13801): GLib-CRITICAL **: 22:35:56.476: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:13801): GLib-GObject-CRITICAL **: 22:35:56.476: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault
```

**Comment by jeremypw** [comment] 2020-09-15 18:33
Please give some more information about the system you are running.  The best way is to send a screenshot of the "About" plug in System Settings.   Are you running in a VM?  Music is crashing for me running Elementary 6 in a VM.

**Comment by jeremypw** [comment] 2020-09-15 18:53
Updatae Music compiled from source runs OK on Elementary 6 in VM

**Comment by iman-salmani** [comment] 2020-09-16 02:12
sorry i forgot this
![about-system](https://user-images.githubusercontent.com/32843050/93284280-8ccd6b00-f7e7-11ea-9239-35adb7a71108.png)
Should I try it in version 6?

**Comment by jeremypw** [comment] 2020-09-16 08:04
Version 6 is not released yet and is unstable so intended mainly for developers and testers. Run in a VM or spare machine.  But Music should run on Hera - I just tried a clean install from AppCenter on Hera 5.1.7 and it did not crash, although I did get lots of the terminal error:

 `** (io.elementary.music:4792): CRITICAL **: 08:38:05.317: music_playback_manager_get_current_media: assertion 'self != NULL' failed`

Looked like an infinite loop but the interface was not blocked.

Was this the first time you used Music or have you been using it successfully in the past?  DId you install from the AppCenter or build it yourself?

The `cannot register existing type` error suggests a version mismatch somewhere.

You could try purging it (`sudo apt purge noise`) and then reinstalling it (`sudo apt install noise`). You would have to then rebuild the library.

To get more information about the crash you could follow the instructions here - https://wiki.debian.org/HowToGetABacktrace

and post the output here.

**Comment by iman-salmani** [comment] 2020-09-16 17:45
> Was this the first time you used Music or have you been using it successfully in the past? DId you install from the AppCenter or build it yourself?

i use pre installed version
previous: start music > click close window > click music icon on plank > terminal output "Segmentation fault" (solve after reboot os)
now: click music icon on plank > Segmentation fault

> You could try purging it (sudo apt purge noise) and then reinstalling it (sudo apt install noise). You would have to then rebuild the library.

purge and install > "Segmentation fault"

solution:
download Music Source code 5.0.5m build and install it
now i only have(output) :+1: 
```
(io.elementary.music:27090): GLib-GObject-CRITICAL **: 22:06:30.564: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:27090): GLib-GObject-CRITICAL **: 22:06:30.781: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:27090): GLib-GObject-CRITICAL **: 22:06:30.882: Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type 'GeeBidirSortedSet' of the property on the interface 'GeeBidirSortedSet'

** Message: 22:06:31.185: AudioPlayer.vala:37: Activating AudioPlayer Device plugin
** Message: 22:06:31.185: CDRom.vala:37: Activating CD-Rom Device plugin
** Message: 22:06:31.185: iPod.vala:37: Activating iPod Device plugin
** Message: 22:06:31.185: LastFM.vala:42: Activating Last.fm plugin

** (io.elementary.music:27090): WARNING **: 22:06:31.649: FileUtils.vala:100: Could not pre-scan music folder. Progress percentage may be off: Error opening directory '/media/iman/Users/Music': No such file or directory
```


note: i used libhandy-0.0-dev but readme file suggested libhandy-1-dev(not available in hera)

**Comment by jeremypw** [comment] 2020-09-17 10:37
Its a bit worrying that the released package crashes for you but as this is the only report (so far) it might be particular to how your system is set up.

**Comment by erfanium** [comment] 2020-12-21 15:06
Same problem:
```sh
erfanium@erfanium-System-Product-Name:~$ io.elementary.music

(io.elementary.music:9203): GLib-GObject-CRITICAL **: 18:34:02.986: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:9203): GLib-GObject-CRITICAL **: 18:34:02.996: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:9203): GLib-GObject-CRITICAL **: 18:34:03.043: Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type 'GeeBidirSortedSet' of the property on the interface 'GeeBidirSortedSet'


(io.elementary.music:9203): GLib-GObject-WARNING **: 18:34:03.188: cannot register existing type 'NoiseViewWrapper'

(io.elementary.music:9203): GLib-CRITICAL **: 18:34:03.188: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:9203): GLib-GObject-CRITICAL **: 18:34:03.188: g_type_register_dynamic: assertion 'parent_type > 0' failed
** Message: 18:34:03.193: AudioPlayer.vala:37: Activating AudioPlayer Device plugin
** Message: 18:34:03.193: LastFM.vala:42: Activating Last.fm plugin
** Message: 18:34:03.193: CDRom.vala:37: Activating CD-Rom Device plugin
** Message: 18:34:03.193: iPod.vala:37: Activating iPod Device plugin

** (io.elementary.music:9203): CRITICAL **: 18:34:03.194: noise_playback_manager_add_playback: assertion 'self != NULL' failed

(io.elementary.music:9203): GLib-GObject-WARNING **: 18:34:03.265: cannot register existing type 'NoiseGStreamerTagger'

(io.elementary.music:9203): GLib-CRITICAL **: 18:34:03.265: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:9203): GLib-GObject-CRITICAL **: 18:34:03.265: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault

```

**Comment by danrabbit** [comment] 2022-01-20 20:21
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:21 UTC
