### ISSUE TITLE
Importing music is slow

### ISSUE THREAD

**Issue by Shnatsel** [elementary/music#296] opened 2018-02-24 01:05 UTC
Importing music to Noise takes a long time: on a fairly powerful machine with 5,000 tracks I get import speed of 1 track per second, which means at takes at about an hour for the initial import and quite noticeable time for any additions. It is also CPU-bound; disk reads are few and far between, but CPU load is 100%.

I've profiled it with `perf` to see where the time is spent. The key findings are:

1. Noise calls `noise_fast_view_resort` for every added track.
1. `noise_list_view_real_refilter` is called three times _for every single added track._

I've generated a flame graph of the profile for easier inspection, but apparently github can't into SVG, so it's attached in gzip: [noise_startup_flame_graph.svg.gz](https://github.com/elementary/music/files/1753673/noise_startup_flame_graph.svg.gz) It is interactive if you open it in a web browser, you can click things to zoom in. If you're not familiar with flame graphs, you can find an intro [here](http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html).

Quick intro to profiling: `sudo perf record --call-graph dwarf -p (pgrep noise)`

If `perf` is missing on your system, install it like this: `sudo apt install linux-tools-generic-hwe-16.04`

You can then inspect the output file in a friendly GUI called [Hotspot](https://github.com/KDAB/hotspot#recording-with-perf-without-super-user-rights) or generate a flame graph you can share using [these scripts](https://github.com/brendangregg/FlameGraph).

Tested on Loki, Noise version `0.4.2+r2134-0+pkg102~ubuntu0.4.1.1`

**Comment by Shnatsel** [comment] 2018-02-24 01:08
As for actually fixing this, I see two approaches.

First, instead of re-processing the entire library we could process only the newly added file. Inserting a new element into a sorted list is actually a `log(n)` operation, you do not need to append it and re-run the entire `n*log(n)` sort. Filtering is even simpler: instead of re-filtering the entire library just decide if that one new file needs to be shown right now or not.

Alternatively, if that is hard or undesirable for whatever reason, we could batch the imported files together and re-run the full and expensive operations not every time a single track is added, but every time 1000 new tracks are added.

**Comment by Nine-H** [comment] 2018-02-24 03:45
the profiling stuff is really cool, I'm going to have to take a look into it. I haven't done extensive testing on music libraries over 1.3GiB but I'll take your word on bad performance, could we ditch the batching and just block the UI till we complete the import then call the resort and filter functions? How long is too long? I recall the HIG says get the window up and show a spinner for slow loading apps.

**Comment by Shnatsel** [comment] 2018-02-24 09:06
I'd find that awkward because importing tracks to library can happen not only on initial import, but also while the app is running, either via "Import to library..." menu item or by simply placing more files in the music folder. Is it OK to block the UI in this case? What if there is a track already playing, does that mean I won't be able to stop playback if import is in progress?

**Comment by Nine-H** [comment] 2018-02-24 11:31
more like we just lock the views and then update when we have the new library, although, the current UI removes the scrub bar and replaces it with a progress bar. we could put that into an infobar or something at the top of the view. But I think UX would have to OK something like that.

**Comment by Shnatsel** [comment] 2018-02-24 12:47
By "lock" do you mean withhold updating them with newly imported tracks, or prohibit user interaction with them completely?

**Comment by Nine-H** [comment] 2018-02-24 12:56
Withhold updating, I can't remember offhand but I think the view object contains an array with the current media library, so it would be fairly straigntforward to just wait because we'd have the old library cached by default. (but don't quote me on that because I might be dead wrong, or it might malfunction when changing views).

**Comment by Shnatsel** [comment] 2018-02-24 13:03
Yeah, I think that's something we should try. And if that fails, we'll just fall back to making update operations process only the newly added track.

**Comment by casasfernando** [comment] 2019-03-16 09:11
This is still true in Juno. I have a 130GB/+21K songs music library and the import is taking a lot of time on a decent powered machine (Intel i7 + 16GB RAM).

**Comment by danrabbit** [comment] 2022-01-20 20:06
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:06 UTC
