### ISSUE TITLE
App usually crashes when loaded: "Timeout reached"

### ISSUE THREAD

**Issue by Sterrs** [elementary/music#58] opened 2017-08-16 13:51 UTC
Running "noise" in the command line produces this output, the app does not open:
```
[INFO 14:47:28.113701] Application.vala:153: Music version: 0.4.1
[INFO 14:47:28.113746] Application.vala:155: Kernel version: 4.10.0-32-generic
Failed to register: Timeout was reached
```

This has been reported multiple times on StackOverflow, but I didn't see it here.
When it does run, I get this error, not sure if it's relevant:
```
[FATAL 15:01:26.931205] [GLib-GObject] g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed
[FATAL 15:01:27.258155] [GLib-GObject] g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed
[FATAL 15:01:27.458378] [GLib-GObject] Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type 'GeeBidirSortedSet' of the property on the interface 'GeeBidirSortedSet'
```

**Comment by BAProductions** [comment] 2021-09-10 12:17
Same in eOS 6 for me not even a restart fixes it

**Comment by danrabbit** [comment] 2022-01-20 19:57
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 19:57 UTC
