### ISSUE TITLE
Columns view - cannot start playing with double click on album ...

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/music#490] opened 2019-02-28 20:11 UTC
... unless another song is already playing.
1. Open app
2. Go to Columns view
3. Double click on the selected Artist / Album
4. Nothing happens
5. Start playing the album by clicking any song
6. From that point, double-clicking any album starts playing it
7. This works even after pausing the song but if you exit the app, it's all over again

**Comment by Mohelm97** [comment] 2019-03-01 00:37
Can't reproduce :( what version are you using?

**Comment by WebShapedBiz** [comment] 2019-03-01 05:33
Hi @Mohelm97.
I'm using Noise version 5.0.3+r2700+pkg113~ubuntu5.0.1 on vanilla Juno, with no hacks or theme modifications or kernel updates or anything naughty. I can throw in a screencast if you'd like.

Thank you for your time and effort.

Cheers.

**Comment by WebShapedBiz** [comment] 2019-03-03 08:51
Update:
I'm getting all sorts of errors starting the Music from the Terminal.
![slika zaslona s 2019-03-03 09-48-56](https://user-images.githubusercontent.com/6765137/53693014-cbccd480-3d99-11e9-926f-ffc0b193174a.png)

The last row is continuously repeating.

**Comment by danrabbit** [comment] 2022-01-20 20:09
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:09 UTC
