### ISSUE TITLE
Dragging multiple tracks into a playlist only adds the first one

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#294] opened 2018-02-16 04:37 UTC
regression in git master, not sure when it emerged.

**Comment by deadpixi** [comment] 2018-11-30 22:44
Confirmed still present in Juno ( noise 5.0.1+r2647).

**Comment by Mohelm97** [comment] 2018-12-01 03:12
Can't reproduce, how can I?

**Comment by deadpixi** [comment] 2018-12-05 03:55
@mohansharma-me My apologies. I can't reproduce it now either. I'm assuming I fat-fingered it somehow.

**Comment by danrabbit** [comment] 2022-01-20 20:07
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:07 UTC
