### ISSUE TITLE
"Rescanning music for changes..." almost three thousand songs, almost 4 hours to process, and freeze at the end of the process

### ISSUE THREAD

**Issue by dioobr** [elementary/music#506] opened 2019-06-05 03:42 UTC
It took almost 4 hours to import all the files into the library, plus four hours to "rescan", this process consumes all RAM, and the application freezes at the end, which forces me to kill the process. This has been my experience. Since I can't complete the process, every time I open the app, it does the "rescan" process. How can I solve this and how can I help you solve this?

My machine configuration:
Macbook 4,1 Late 2007
Intel Core 2 Duo 2,4 GHz
6GB RAM / 240GB SSD
Elementary OS Juno (Updated)

**Comment by SeanyMCP** [comment] 2019-07-20 17:02
Same here, big libraries suffocates the app to death (I have 650 Gb of music).

**Comment by cizordj** [comment] 2019-12-21 01:06
Me too, I have a thousand of records on my second hard drive and it is formatted as BTRFS. It takes one minute to scan, even though it's not cool to be waiting.

**Comment by tonywei92** [comment] 2020-05-15 06:19
Any fix?

**Comment by jeremypw** [comment] 2020-10-04 09:36
This is effectively a duplicate of #311

**Comment by danrabbit** [comment] 2022-01-20 20:16
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:16 UTC
Labels: Status: Duplicate
