### ISSUE TITLE
Music crashes if you press Play/Pause when no track is playing

### ISSUE THREAD

**Issue by Shnatsel** [elementary/music#317] opened 2018-03-27 21:09 UTC
Steps to reproduce:

1. Start Music, wait for library rescan to complete
1. Press Play/Pause media key :boom: Music crashes

Found on Loki, Noise version `0.4.2+r2134-0+pkg102~ubuntu0.4.1.1`

**Comment by danrabbit** [comment] 2022-01-20 20:06
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:06 UTC
