### ISSUE TITLE
SmartPlaylist ANY/ALL combobox doesn't save

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#221] opened 2017-12-21 06:46 UTC
the bug is in database.vala, which wants to save every `SmartPlaylist`'s `conditional` property as an `int` but `SmartPlaylist.ConditionalType` is a weird public `enum` that won't cast to `int` and breaks other stuff if you get rid of the booleans in it's declaration.

**Comment by danrabbit** [comment] 2022-01-20 20:02
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:02 UTC
