### ISSUE TITLE
Conflict: music doesn't follow elementary naming scheme, conflicts with OpenFOAM

### ISSUE THREAD

**Issue by EidoJ** [elementary/music#496] opened 2019-03-26 20:43 UTC
One cannot install both elementary Music and OpenFOAM on the same system due to conflicting files. During install using apt, the following error is issued:
```
dpkg: error processing archive /var/cache/apt/archives/openfoam_4.1+dfsg1-2_amd64.deb (--unpack):
 trying to overwrite '/usr/share/man/man1/noise.1.gz', which is also in package noise 5.0.3+r2700+pkg113~ubuntu5.0.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
```

**Comment by danrabbit** [comment] 2022-01-20 20:18
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:18 UTC
Labels: Status: Confirmed
