### ISSUE TITLE
Music/Noise generates continuous errors

### ISSUE THREAD

**Issue by ghabit** [elementary/music#563] opened 2020-01-07 17:39 UTC
Music\Noise generates continuous errors
kh@elementaryospc:~$ io.elementary.music 
```

(io.elementary.music:16261): GLib-GObject-CRITICAL **: 20:03:06.335: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:16261): GLib-GObject-CRITICAL **: 20:03:06.442: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:16261): GLib-GObject-CRITICAL **: 20:03:06.528: Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type 'GeeBidirSortedSet' of the property on the interface 'GeeBidirSortedSet'


(io.elementary.music:16261): GLib-GObject-WARNING **: 20:03:14.622: cannot register existing type 'NoiseViewWrapper'

(io.elementary.music:16261): GLib-CRITICAL **: 20:03:14.623: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:16261): GLib-GObject-CRITICAL **: 20:03:14.623: g_type_register_dynamic: assertion 'parent_type > 0' failed
** Message: 20:03:14.633: LastFM.vala:42: Activating Last.fm plugin
** Message: 20:03:14.633: AudioPlayer.vala:37: Activating AudioPlayer Device plugin
** Message: 20:03:14.633: CDRom.vala:37: Activating CD-Rom Device plugin
** Message: 20:03:14.633: iPod.vala:37: Activating iPod Device plugin

(io.elementary.music:16261): GLib-GObject-WARNING **: 20:03:14.635: invalid (NULL) pointer instance

(io.elementary.music:16261): GLib-GObject-CRITICAL **: 20:03:14.635: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(io.elementary.music:16261): GLib-GObject-WARNING **: 20:03:14.635: invalid (NULL) pointer instance

(io.elementary.music:16261): GLib-GObject-CRITICAL **: 20:03:14.635: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(io.elementary.music:16261): GLib-GObject-WARNING **: 20:03:14.635: invalid (NULL) pointer instance

(io.elementary.music:16261): GLib-GObject-CRITICAL **: 20:03:14.635: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:14.636: noise_playback_manager_add_playback: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:16.108: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:16.108: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

(io.elementary.music:16261): Gtk-WARNING **: 20:03:16.177: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

** (io.elementary.music:16261): CRITICAL **: 20:03:16.308: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:16.308: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:16.308: Album.vala:163: Нераспознанный формат файла изображения

** (io.elementary.music:16261): CRITICAL **: 20:03:16.514: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:16.514: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:16.731: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:16.731: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:16.932: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:16.932: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:17.132: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:17.133: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:17.333: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:17.334: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:17.535: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:17.535: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:17.736: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:17.736: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:17.937: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:17.937: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:18.137: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:18.137: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:18.339: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:18.339: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:18.539: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:18.539: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:18.740: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:18.740: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:18.940: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:18.940: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:19.141: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:19.141: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:19.342: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:16261): CRITICAL **: 20:03:19.342: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

```
Started in terminal because last.fm scrobbling does not working, in hope for some output.

**Comment by danrabbit** [comment] 2022-01-20 20:16
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:16 UTC
