### ISSUE TITLE
When clicking on a track to play, the album cover appears.

### ISSUE THREAD

**Issue by dcharles525** [elementary/music#473] opened 2019-01-02 00:39 UTC
Also if I close the album cover the music stops playing.

Here is an example: 
![screenshot from 2019-01-01 19 38 32](https://user-images.githubusercontent.com/4961680/50577753-e831ac80-0dfc-11e9-8563-633fd43e5d66.png)

**Comment by benjaminky** [comment] 2019-05-27 09:45
the [ringtone](https://ringtonefreedownload.net) album cover appears, I think there is a certain command that is run when you click

**Comment by Mohelm97** [comment] 2019-05-27 11:31
Hi @dcharles525 
I couldn't reproduce this, could you tell us more information? like which version are you using, the log before the crash?

**Comment by dcharles525** [comment] 2019-05-28 00:17
I tried this again and got the output below. When I closed the popup album art I see that there is a warning. (bottom of debug)
```
(io.elementary.music:14672): GLib-GObject-CRITICAL **: 20:14:37.246: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:14672): GLib-GObject-CRITICAL **: 20:14:37.300: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:14672): GLib-GObject-CRITICAL **: 20:14:37.363: Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type 'GeeBidirSortedSet' of the property on the interface 'GeeBidirSortedSet'


(io.elementary.music:14672): GLib-GObject-WARNING **: 20:14:38.375: cannot register existing type 'NoiseViewWrapper'

(io.elementary.music:14672): GLib-CRITICAL **: 20:14:38.375: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:14672): GLib-GObject-CRITICAL **: 20:14:38.375: g_type_register_dynamic: assertion 'parent_type > 0' failed
** Message: 20:14:38.381: iPod.vala:37: Activating iPod Device plugin
** Message: 20:14:38.384: AudioPlayer.vala:37: Activating AudioPlayer Device plugin
** Message: 20:14:38.384: CDRom.vala:37: Activating CD-Rom Device plugin
** Message: 20:14:38.384: LastFM.vala:42: Activating Last.fm plugin

** (io.elementary.music:14672): CRITICAL **: 20:14:38.386: noise_playback_manager_add_playback: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:39.129: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:39.129: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:39.330: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:39.330: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:39.531: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:39.531: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:39.732: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:39.732: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:39.932: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:39.932: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:40.133: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:40.133: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:40.333: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:40.333: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:40.534: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:40.534: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:40.735: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:40.735: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:40.935: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:40.935: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:41.136: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:41.136: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:41.337: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:41.337: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:41.538: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:41.538: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:41.739: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:41.739: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:41.939: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:41.939: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:42.140: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:42.140: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:42.341: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:42.341: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:42.541: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:42.541: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:42.742: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:42.742: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:42.943: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:42.943: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:43.144: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:43.144: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:43.345: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:43.345: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:43.546: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:43.546: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:43.746: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:43.746: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:43.947: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:43.947: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:44.148: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:44.148: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:44.349: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:44.349: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:44.550: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:44.550: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:44.751: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): CRITICAL **: 20:14:44.751: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:14672): WARNING **: 20:14:44.878: Streamer.vala:154: Error: Output window was closed
```

**Comment by Nine-H** [comment] 2019-05-28 00:54
Is the track an .mp4? could be a video file I know gstreamer likes to pop a video buffer in a new window by default.

**Comment by dcharles525** [comment] 2019-05-28 12:25
Nope its a .aiff file

**Comment by danrabbit** [comment] 2022-01-20 20:09
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:09 UTC
