### ISSUE TITLE
Only a small portion of music files show up in Music.

### ISSUE THREAD

**Issue by ghost** [elementary/music#474] opened 2019-01-11 18:09 UTC
I seem to be having an issue with Music in regards to how much of my library shows up in the app. I've got ~7,000 songs in my Music folder, but only about ~2000 of those actually appear in Music. (My music folder is set correctly, yes.) I can still drop files in to play them or just open them from Files, but Music itself doesn't show my full library.

EDIT: All files are MP3 in regards to both encoding and container format.

Music version: 5.0.2

System information:
```
System:    Host: schyken-ryzen-horizon Kernel: 4.19.13-041913-generic x86_64 bits: 64 gcc: 8.2.0
           Desktop: Gnome  (Gtk 3.22.30-1ubuntu1) Distro: elementary OS 5.0 Juno
Machine:   Device: desktop Mobo: ASUSTeK model: PRIME B350-PLUS v: Rev X.0x serial: N/A
           UEFI: American Megatrends v: 4023 date: 08/20/2018
CPU:       8 core AMD Ryzen 7 2700 Eight-Core (-MT-MCP-) arch: Zen rev.2 cache: 4096 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm) bmips: 54296
           clock speeds: max: 3400 MHz 1: 1356 MHz 2: 1357 MHz 3: 3393 MHz 4: 3387 MHz 5: 1356 MHz 6: 1356 MHz
           7: 1356 MHz 8: 1355 MHz 9: 1375 MHz 10: 1374 MHz 11: 1374 MHz 12: 1374 MHz 13: 1375 MHz 14: 1374 MHz
           15: 1374 MHz 16: 1374 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Vega [Radeon RX Vega] bus-ID: 0c:00.0
           Display Server: x11 (X.Org 1.19.6 ) drivers: ati,amdgpu (unloaded: modesetting,fbdev,vesa,radeon)
           Resolution: 2560x1440@59.95hz
           OpenGL: renderer: Radeon RX Vega (VEGA10 / DRM 3.27.0 / 4.19.13-041913-generic, LLVM 6.0.0)
           version: 4.5 Mesa 18.0.5 Direct Render: Yes
Audio:     Card-1 Advanced Micro Devices [AMD] Family 17h (Models 00h-0fh) HD Audio Controller
           driver: snd_hda_intel bus-ID: 0e:00.3
           Card-2 Advanced Micro Devices [AMD/ATI] Device aaf8 driver: snd_hda_intel bus-ID: 0c:00.1
           Card-3 Creative Labs Sound Core3D [Sound Blaster Recon3D / Z-Series]
           driver: snd_hda_intel bus-ID: 09:00.0
           Card-4 Logitech HD Pro Webcam C920 driver: USB Audio usb-ID: 003-002
           Card-5 C-Media driver: USB Audio usb-ID: 001-002
           Sound: Advanced Linux Sound Architecture v: k4.19.13-041913-generic
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 port: f000 bus-ID: 04:00.0
           IF: enp4s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:    HDD Total Size: 2250.5GB (2.8% used)
           ID-1: /dev/nvme0n1 model: Samsung_SSD_960_EVO_250GB size: 250.1GB
           ID-2: /dev/sda model: WDC_WDS500G2B0A size: 500.1GB
           ID-3: /dev/sdb model: WDC_WDS500G2B0A size: 500.1GB
           ID-4: /dev/sdc model: WDC_WDS500G2B0A size: 500.1GB
           ID-5: /dev/sdd model: WDC_WDS500G2B0A size: 500.1GB
Partition: ID-1: / size: 224G used: 21G (10%) fs: btrfs dev: /dev/nvme0n1p3
           ID-2: /boot size: 946M used: 221M (25%) fs: ext4 dev: /dev/nvme0n1p2
           ID-3: /home size: 224G used: 21G (10%) fs: btrfs dev: /dev/nvme0n1p3
           ID-4: swap-1 size: 8.01GB used: 0.00GB (0%) fs: swap dev: /dev/nvme0n1p4
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: N/A mobo: N/A gpu: 32.0
           Fan Speeds (in rpm): cpu: 0
Info:      Processes: 406 Uptime: 1 day Memory: 2917.3/32161.8MB Init: systemd runlevel: 5 Gcc sys: 7.3.0
           Client: Shell (bash 4.4.191) inxi: 2.3.56
```

**Comment by danrabbit** [comment] 2022-01-20 20:09
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:09 UTC
