### ISSUE TITLE
Import to Library causes a GTK fatal error

### ISSUE THREAD

**Issue by intercaetera** [elementary/music#70] opened 2017-09-10 18:57 UTC
Upon clicking the gear icon and selecting Import to Library this happens:

```
[FATAL 20:57:27.073653] [Gtk] gtk_file_filter_get_name: assertion 'GTK_IS_FILE_FILTER (filter)' failed
[WARNING 20:57:27.089282] [Gtk] gtk_window_set_titlebar() called on a realized window
```

Using elementary OS with i3wm.

**Comment by danrabbit** [comment] 2022-01-20 19:57
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 19:57 UTC
