### ISSUE TITLE
RDNN everywhere

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#132] opened 2017-12-03 03:56 UTC
goodbye `org.pantheon.noise/noise/music` hello `io.elementary.music`

there's some work towards this in the meson branch.

**Comment by lainsce** [comment] 2017-12-03 04:04
Usually, one thing changes per PR, so let the Meson PR be only for Meson, create a new one for RDNN, this makes reviews easier.

**Comment by Nine-H** [comment] 2017-12-03 04:10
meson does a whole heap of validation stuff so the paths of some files need to change. Can I get a review on what I have so far? I want to know what's left to get it into master so I can do the fun vala stuff with everyone else :cry:

**Comment by lainsce** [comment] 2017-12-03 04:15
Well, I'm not a reviewer, but I know how the reviews are done. Try making the meson branch as atomic as possible, or add in the PR description that one needs the other PR first or something.

**Comment by danrabbit** [comment] 2022-01-20 20:00
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:00 UTC
