### ISSUE TITLE
doesn't show in application menu

### ISSUE THREAD

**Issue by antayera** [elementary/music#579] opened 2020-04-03 10:47 UTC
Default music player doesn't show up in Applications menu. It is installed (and I tried to reinstall it > restart > still same issue). If I want to open it, I have to go to the AppCenter.
![Schermafdruk van 2020-04-03 12-31-12](https://user-images.githubusercontent.com/63100962/78352797-42de2900-75a9-11ea-8ab2-0c0e8102c931.png)

**Comment by danrabbit** [comment] 2022-01-20 20:16
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:16 UTC
