### ISSUE TITLE
RDNN package name

### ISSUE THREAD

**Issue by cassidyjames** [elementary/music#597] opened 2020-09-11 22:53 UTC
It's still `noise`. #132 seems to be focused on internal namespacing, but the package itself needs to be updated as well.

**Comment by danrabbit** [comment] 2022-01-20 20:21
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:21 UTC
