### ISSUE TITLE
[NOT EXPECTED] Doesn't "close", come over other windows and more...

### ISSUE THREAD

**Issue by elSolus** [elementary/music#646] opened 2021-07-29 07:13 UTC
## What Happened

Hey, developers, please look into the following problems:

Step by step:
1. I double click the mp3 which loads it in Music (Okay).
2. Then I close Music by clicking the cross in the corner (Well, not okay because...).
3. It just goes out of sight but doesn't actually close, and keeps playing music in the background (Not okay, because I "closed").
4. Now, no way to go to the "currently playing" song as I "closed" Music (Not okay).
5. I double click the mp3 again and this shows Music in the dock. (Well...)
6. It just shows there, I have to click on the icon in the dock again to actually open it (Not okay).
7. Even then, it doesn't come on top of all other windows as the active one. Still after that "launch", it hides behind and I have to click anywhere on the app window to bring it forward. (Very not okay).
8. Only way to stop (M)usic is to pause the song and 'close' it.
9. That's too many steps for a simple thing. All this made me install another music player which I would've never done if..., you know. Check the video for more:

https://user-images.githubusercontent.com/77105020/127447493-0258fddc-bc2d-426a-ad98-145c4ba25766.mp4

## Expected Behavior

All those "not okays" should be "okays".

## Steps to Reproduce

1. Launch Music, play some music
2. Close it (it actually doesn't. 1st)
3. Now try finding it (it's nowhere. 2nd)
4. And more (please check the video)

## Platform Information

OS: elementary 5.1.7 Hera
CPU: Intel i5 3330
RAM: 6GB
Mobo: Intel DH61WW

**Comment by ryonakano** [comment] 2021-07-30 08:10
Hi thanks for your reporting with steps to reproduce and the screenshot, it made me easy to understand. However, a few things I'd like you to do in the next bug reports:

- **Please refrain from mentioning someone unless you have a specific reason**. Dan and Cassidy are the core members of elementary and they're busy in many things, so especially it's not recommended to mention them. It's OK to mention one who commented against your issue report though.
- **Make sure you create one issue report per issue.** Your issue report seems to contain at least two issues, 1) the app keep running nevertheless you close it and 2) the app doesn't appear at the top of other windows. Please check what you're reporting before submitting issue reports.

--------

The followings are comments against your issue.

- Regarding to the issue 1), it's a "feature" of the app; even if you happen to close the app, you should be able to reopen it from Sound Indicator.
- Regarding to the issue 2), I'll check if possible to reproduce it on my install.

**Comment by elSolus** [comment] 2021-07-30 11:49
Hey, thanks @ryonakano . I did the mentions in case nobody noticed (initially I didn't, then I was worried it was going unnoticed so...) I understand why I shouldn't mention them. Now, should I edit this one to make it a one issue and create new for the other, or let it stay as it is and be careful in the future?

**Comment by ryonakano** [comment] 2021-07-31 09:26
Your activity is notified to [everyone who watches this repository](https://github.com/elementary/music/watchers) even if you don't mention, so you don't need to worry about that :) But not everyone has enough time to look each report, so making readable issue reports can get more chance to get interest from organization members.

Yes, would you make a new issue? But before submitting, check if your issue is already reported by searching. 🙏🏻

**Comment by danrabbit** [comment] 2022-01-20 20:20
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:20 UTC
