### ISSUE TITLE
Use better notification defaults

### ISSUE THREAD

**Issue by alexgleason** [elementary/music#324] opened 2018-04-07 16:50 UTC
Not sure if this is even an option for apps in elementary yet, but if we can set default options about how an app handles notifications I think at the very least, Music should not cause notifications to pile up after each song plays:

![screenshot from 2018-04-07 12 47 44](https://user-images.githubusercontent.com/3639540/38457675-f495a996-3a61-11e8-9396-7ece774750ed.png)

I don't expect much disagreement here, because nobody wants to actually open Music between each track, and they don't care about songs that played previously. It's annoying to dismiss notifications from this app.

In addition, I would consider disabling sounds, because they impact the listening experience. I don't feel as strongly about this, however.

![screenshot from 2018-04-07 12 48 01](https://user-images.githubusercontent.com/3639540/38457710-40253ae8-3a62-11e8-800f-e5850492f696.png)

**Comment by danrabbit** [comment] 2022-01-20 20:06
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:06 UTC
