### ISSUE TITLE
music sync slows the app on every startup

### ISSUE THREAD

**Issue by Fabioulloaev** [elementary/music#606] opened 2020-10-03 21:18 UTC
my music library weighs 14gb, and every time I open Noise it starts to scan everything again .. Consuming resources and making the app Slow

**Comment by jeremypw** [comment] 2020-10-04 09:34
This issue has been previously reported - first at #311.  The app needs to monitor the library for any changes while it was closed but it should not impact the responsivity.

**Comment by danrabbit** [comment] 2022-01-20 20:20
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:20 UTC
Labels: Status: Duplicate
