### ISSUE TITLE
Cannot select and perform operations on multiple songs at once

### ISSUE THREAD

**Issue by lucian-devtel** [elementary/music#503] opened 2019-04-23 09:14 UTC
Sometimes (7 in 10 tries) it is impossible to select multiple songs and perform some action on the selected items in the songs list. I select the songs, then when I try to right-click on them, the items get deselected.
This issue occurs very often especially after using the app for a couple of minutes and because of it is is impossible to add any items to a playlist for example. All functionality related to a group of songs becomes inaccessible.

[https://cloud.devtelsoftware.com/index.php/s/j4GpYadBQnRJm93](url)

This happens both with trackpad and mouse.
I have attached a screencast of the issue. My system is an Elementary OS JUNO.

**Comment by benjaminky** [comment] 2019-05-27 09:35
I think in the future github can support selecting multiple [ringtone](url=https://ringtone123.net) songs (objects)

**Comment by danrabbit** [comment] 2022-01-20 20:17
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:17 UTC
