### ISSUE TITLE
context menu analogue aimp

### ISSUE THREAD

**Issue by evgeniymalyanov** [elementary/music#77] opened 2017-10-07 17:16 UTC
add in menu option add to clear playlist (clear playlist before add new tracks)

![image](https://user-images.githubusercontent.com/21965984/31309983-c65871a8-aba0-11e7-9aec-196656274c21.png)
![dsc_0005](https://user-images.githubusercontent.com/21965984/31310204-bed77fba-aba4-11e7-872f-49537a423143.JPG)

**Comment by danrabbit** [comment] 2022-01-20 19:58
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 19:58 UTC
