### ISSUE TITLE
CTD when the app has many music to load

### ISSUE THREAD

**Issue by ugoCesano** [elementary/music#567] opened 2020-02-04 20:24 UTC
The app crashes when I want to load many flac files (~10GB)

**Comment by danrabbit** [comment] 2022-01-20 20:16
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:16 UTC
