### ISSUE TITLE
Starting a track and clicking the previous track button causes playback to stop.

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#264] opened 2018-01-30 11:27 UTC
```
[DEBUG 22:26:18.738306] ViewWrapper.vala:447: SETTING MEDIA [NOISE_VIEW_WRAPPER_HINT_READ_ONLY_PLAYLIST]
[DEBUG 22:26:18.753624] LibraryWindow.vala:652: UPDATE SENSITIVITIES
[DEBUG 22:26:18.758911] LibraryWindow.vala:935: playback stopped
[DEBUG 22:26:18.759991] LibraryWindow.vala:652: UPDATE SENSITIVITIES
[DEBUG 22:26:18.760803] LibraryWindow.vala:935: playback stopped
[DEBUG 22:26:18.761350] LibraryWindow.vala:652: UPDATE SENSITIVITIES
```
I don't think the debug message from ViewWrapper.vala is very useful because it always returns NOISE_VIEW_WRAPPER_HINT_READ_ONLY_PLAYLIST

**Comment by jeremypw** [comment] 2021-05-05 15:39
Closing as this is an old issue that does not meet current standards for bug reports.  The expected behaviour is not discussed.  Please feel free to open a new report if the behaviour is still an issue in the latest version.

**Comment by danrabbit** [comment] 2022-01-20 20:07
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.

**Closed by danrabbit** 2022-01-20 20:07 UTC
