### ISSUE TITLE
Music doesn't stop playing files (.opus) upon closing programme

### ISSUE THREAD

**Issue by baimafeima** [elementary/music#59] opened 2017-08-21 20:10 UTC
This is a bug report which was first raised here: https://dev.solus-project.com/T4355

_Music_ doesn't stop playing files (in my case .opus files) upon closing the programme.

When launching it from the terminal with "noise" I get the following error message:
```
[INFO 03:50:55.331152] Application.vala:153: Music version: 0.4.0.3
[INFO 03:50:55.331199] Application.vala:155: Kernel version: 4.9.26-25.lts
[FATAL 03:50:55.435380] [GLib-GObject] g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed
[FATAL 03:50:55.477261] [GLib-GObject] g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(noise:1980): Gtk-WARNING **: Theme parsing error: <data>:11:22: The :focused pseudo-class is deprecated. Use :focus instead.
[FATAL 03:50:55.659595] [GLib-GObject] Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type 'GeeBidirSortedSet' of the property on the interface 'GeeBidirSortedSet'
[INFO 03:50:55.906159] CDRom.vala:37: Activating CD-Rom Device plugin
[INFO 03:50:55.906244] AudioPlayer.vala:37: Activating AudioPlayer Device plugin

(noise:1980): Gtk-WARNING **: Theme parsing error: <data>:11:22: The :focused pseudo-class is deprecated. Use :focus instead.
[WARNING 03:50:56.050425] [Gtk] (gtkicontheme.c:5493):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 03:50:56.050473] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
```

**Comment by cassidyjames** [comment] 2017-08-21 20:12
By design, Music does not stop playing when the window is closed; you can pause the music from the audio indicator, or pause before closing the window.

**Closed by cassidyjames** 2017-08-21 20:12 UTC

**Comment by baimafeima** [comment] 2017-08-21 20:15
Could this at least be made optional in the preferences? When closing it, I naturally expect all music-related processes to stop. When minimizing I expect it to continue playing music in the background. I think this is a valid bug as elementary software is increasingly being used on other operating systems and desktop environments and should be made more distro-agnostic. 

What about the rest of error message? Any issues that need to be addressed there?

**Comment by cassidyjames** [comment] 2017-08-21 20:49
It looks like there are a few options settable via dconf. namely ` /org/pantheon/noise/settings/close-while-playing`. This could be set by downstream packaging if that fits with their DE better, but the current behavior is consistent with elementary apps. I don't see this becoming a user-facing preference.
