### ISSUE TITLE
Crash when double-clicking on an album or artist in the column browser

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/music#97] opened 2017-11-27 18:42 UTC
Well, that's a new low for an already bad app.
After upgrade to 0.4.2. Noise exits after clicking play buttin with this error message:

> ERROR:arraylist.c:964:gee_array_list_real_get: assertion failed: (index >= 0)

EDIT:
If I click on artist then double click on the album the app will exit. However, if I click on artist, select an album and double-click on the first song, the whole album will go to queue and be played from there. And no, I'm not joking, this is for real.

**Comment by Bat41** [comment] 2017-12-02 17:08
In fact, it looks like it happens when you double click on an artist or an album in the column browser.

**Comment by Bat41** [comment] 2017-12-02 21:12
Duplicate of #91

**Closed by Bat41** 2017-12-02 21:12 UTC
Labels: Priority: Medium, Status: Confirmed
